### ISSUE TITLE
Provide a cancel option to the properties dialogues

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#100]
When I change something in the dialog (e.g. change class, change relation) in Odalic UI, it is directly changed. It would be good to have the possibility to confirm the changes or withdraw (by pressing cancel or "x" in the corner of the dialog) at the end.

**Comment by brodecva** [comment]
@tomas-knap continues (in Czech):
> Nicmene toto je trochu narocnejsi, bo by bylo potreba si pamatovat puvodni stav a pripadne byt schopen resetnout do puvodniho stavu. Pripadne si pamatovat zmeny a provest je az po potvrzeni. Mozna by slo vytvorit si kopii grafu, tam delat zmeny a pak tenhle graf bud zahodit a nebo prohlasit za novy graf.

**Comment by brodecva** [comment]
Hi, @istvan-satmari , for the 4th iteration, just try to think about it, how hard would it be to implement, what time would it take and so on...

**Comment by tomas-knap** [comment]
Yes, seems like this is quite hard, @istvan-satmari please rather help Kata with her issues for iteration 4. @brodecva, move to 5th iter?

**Comment by istvan-satmari** [comment]
I don't think it's hard to implement... But I can't make the descision. @KataBoku directly works with the result object sent by the server, which is then mirrored by the GUI. (The binding of GUI to data is basically 1:1)
To implement this I suppose we would need to:
1) clone the result object and temporarily save it
2) provided the 'cancel' button was pressed, replace the current result object with the temporary clone
- I believe it should be this simple, but I'll have to discuss with @KataBoku

**Comment by tomas-knap** [comment]
Ok, thanks for investigating that! We should realize that, because it was also pointed couple of times during the workshop in September

**Comment by brodecva** [comment]
@istvan-satmari Thanks! Assigning @KataBoku and moving to 5th iteration.

**Comment by brodecva** [comment]
@KataBoku @istvan-satmari Reassigning beack to @istvan-satmari , as @KataBoku has alrady too much high priority issues. You can still @istvan-satmari consult her about it.

**Comment by istvan-satmari** [comment]
changing prio to low due to a shortage of time.
though not hard to implement from a logical point of view, will take a significant time (mainly because I would be dealing with a code that is not mine)

**Comment by tomas-knap** [comment]
As we discussed, just please change the "OK" button to close and leave it as it is. Then it can be closed

**Comment by tomas-knap** [comment]
overlapping with https://github.com/odalic/odalic-ui/issues/247

**Comment by istvan-satmari** [comment]
Seems like @KataBoku  solved this one, so closed.
