### ISSUE TITLE
Make the UI comply with history browser controls (back, forward buttons)

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#101]
Back button was not working properly - when observing result of the task, then "back" button gets you to "loading state".

**Comment by istvan-satmari** [comment]
Solved. May be a problem later: if a user changes loading screen while the result is computing (e.g. by going back to the create-new-task screen),  the history will be 'messy'. 
Proposed solution for later:
- 'loading screen' should  not be a separate screen but rather a 'loading' icon should be displayed on the 'create-new-task' screen after submitting a task.

**Comment by tomas-knap** [comment]
What does that mean that "the history will be 'messy'. "? What will happen if I start conversion, go back, create new task and start another conversion? There are ids for conversion tasks, right? So it should work correctly, or not?
