### ISSUE TITLE
User may get further information about the resource

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#108]
See https://grips.semantic-web.at/x/bwGBB .

Two things: 
- being able to click on the resource in the detail and depict result of the HTTP GET. 
- being able to click on the resource directly on the Table and depict result of the HTTP GET (if this is difficult, we may postpone)

Do not use lodlive/lodview for that, leave it as it is for now, this is another feature (using different approach than the chain icon and lodview/lodlive). So please  implement this feature in a simple way by just having a browser window which appears when e.g. someone stays with the mouse over a resource or clicks on some button - as a result HTTP GET is raised and if there is some reasonable output provided by the external server, it is depicted.

**Comment by tomas-knap** [comment]
lodlive/lodview integration

**Comment by brodecva** [comment]
> For that, lodlive/lodview can be used. Test whether this is satisfactory or not

Yes, in case of the lodwiew, there is still one issue to be solved ( https://github.com/odalic/LodView/issues/3 ).

The lodlive link might be viable. In contrast to browsing the lodlive in order to change the selected entity or class, this would be strictly read only, so it should be pretty straightforward to add.

Main concern: the same instance of lidlive as the one for selecting a resource should be used, so @KataBoku , make sure that this read only use case does not collide with the one, that sends messages across the Odalic/lodlive boundary.

**Comment by brodecva** [comment]
I am a bit sceptical if we made it in the 4th iteration, though. @KataBoku has plenty of work to do with re-factoring and bugs.

**Comment by brodecva** [comment]
@tomas-knap If you won't mind I will move it to the 5th iteration. After I will have the time needed for the 4th one estimated, I will either move this issue to the 4th or leave it in the 5th.

**Comment by tomas-knap** [comment]
Please leave the lod live/lod view as it is. And implement that in a simple way by just having a browser window which appears when e.g. someone stays with the mouse over a resource or clicks on some button - as a result HTTP GET is raised and if there is some reasonable output provided by the external server, it is depicted.

**Comment by tomas-knap** [comment]
So as we discussed on Friday the idea is: 
- for Table in Step 1 (Classification & Disamb), please make the URL clickable - it opens resource description in the new tab. Please test that it works also in case of using prefixes - so when clicking on prefixed URL, full URL should be used. Also please add e.g. a small icon next to lodlive icon for the same functionality in the class/disamb dialog detail.
- In case of relations, please just include that small icon next to lodlive icon for being able to see description of the relation from the relation detail dialog.

**Comment by brodecva** [comment]
Finished in #319 .
