### ISSUE TITLE
(?) Single task overview

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#11]
- Create a "single task overview".
- This will probably be an extension of (1) "task creation". It will presumably include more info about a single task, such as "feedback".
- This issue will be later specified in more detail. It is also questionable whether the functionality is necessary for the first iteration.

**Comment by tomas-knap** [comment]
@brodecva Not aimed for 2.iter, right?

**Comment by brodecva** [comment]
> Not aimed for 2.iter, right?

Yeah, I missed this one during the clean-up. It is also highly likely that this issue will be superseded by another as the planning will go on.
