### ISSUE TITLE
Alter the relations graph to enable advanced locking and removal

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#110]
https://grips.semantic-web.at/x/CAKBB and https://grips.semantic-web.at/x/SgGBB

**Comment by istvan-satmari** [comment]
Lock icon added, though not sure what to do next until the locking functionality is in the "/taskresult/" properly implemented.

**Comment by brodecva** [comment]
Waits for #112 .

**Comment by istvan-satmari** [comment]
This is done, but the 'hacks' necessary to complete the task will need to be removed.
