### ISSUE TITLE
Wrapping of 'exports' (REST API v 3.0)

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#113]
The problem is basically the fact that the data of 'exports' is wrapped:
{"status":200,"type":"DATA","payload":context":"http://www.w3.org/ns/csvw","url":"iv1.csv","tableSchema":{" ...

this is not very appreciated since there is little we can do on the client's side. If we use AJAX to download and modify the 'export' (pull only the 'payload' from the provided JSON), the user is then unable to save the data. (JS cannot create a file, only open a link.)
Luckily this applies only to 'JSON' format, both CSV and RDF work fine.
Thanks.

**Comment by brodecva** [comment]
Yeah, that is a an oversight on my part. I always meant to send the export unwrapped, and I do so in the case of JSON+LD for example. I will fix that.

**Comment by brodecva** [comment]
Fixed and pushed to the feature-rest-overhaul branch.
