### ISSUE TITLE
Knowledge bases list UI

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#12]
- This issue will be later specified in more detail. It is also questionable whether the functionality is necessary for the first iteration.

**Comment by brodecva** [comment]
Will be read only, and must wait for the API to materialize first.

**Comment by brodecva** [comment]
@tomas-knap additional info:
> There should be list of knowledge bases, which users may use in the tasks - this is a must. If time, it should be also possibility to click on the knowledge base to get read-only information about that KB from config file.

**Comment by tomas-knap** [comment]
So basically during task configuration one has to see the available knowledge bases taken from the config file in the list box:

![screen shot 2016-11-30 at 12 49 25](https://cloud.githubusercontent.com/assets/3014917/20751385/c087f7ca-b6fb-11e6-846e-d39b530c7b54.png)

**Comment by tomas-knap** [comment]
@brodecva Marked as won't fix - but I guess we agreed that the select box in the task configuration creation page will reflect the KBs' names defined in the config files, right? Is there another issue for that?
