### ISSUE TITLE
Primary knowledge base can be changed, but it is not saved

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#124]
It makes sense to just fix the primary base in the UI (prevent modification) and be done with it (for this iteration)-

**Comment by brodecva** [comment]
Reopening.

**Comment by tomas-knap** [comment]
@brodecva Please describe here a bit more where the problem is, what needs to be done. 
How can I change the primary KB?

**Comment by brodecva** [comment]
Fixed as of https://github.com/odalic/odalic-ui/commit/6a281c5196fd6f97a439cabed9d3612934154261 .
