### ISSUE TITLE
LodLive link - make sure that it behaves correctly for all KBs

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#127]
As it is now, the user is hardly aware that he can click the chain to access the LodLive view. Make the chain icon more prominent (larger, contoured, changing when hovered).

**Comment by tomas-knap** [comment]
Check that it behaves correctly for non-dbpedia KBs, currently it seems that empty iframe is opened which hides the rest...

**Comment by tomas-knap** [comment]
@brodecva Please assign to someone to test whether lodlive works also with other KBs then Dbpedia.

**Comment by tomas-knap** [comment]
Write down status: 
- does that work also with non-dbpedia KB? Does it end with error or just nothing is displayed.

**Comment by brodecva** [comment]
Let's make it simple: the LodLive link should work for DBpedia (at least english one) for the others it can be clicked, but the user must be able to close the view and return back to the app. Period. Thx!

**Comment by brodecva** [comment]
@josef-janousek Let us know if it fails for the AdequatePP.

**Comment by josef-janousek** [comment]
Seems that it works without error also for non-DBpedia KBs - it displays just clickable URI (see the picture with resource from Adequate) of the resource. The "cross" icon for closing the iframe works correctly.
![lodlive-adequate](https://cloud.githubusercontent.com/assets/17772934/23344520/50be2900-fc7e-11e6-81b8-4cf2459e5080.png)
