### ISSUE TITLE
No processing results display for the first result page until i hit Next and then Previous to get back

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#128]
This needs to be fixed.

**Comment by istvan-satmari** [comment]
I believe this is connected to "scope.locked is undefined" problem.
Usually happens when a user displays a result and changes something (e.g. locks a concept). It seems to be non-stateless, i.e. when I do this and then go back to taskconfigs and then again head to the result, the error is thrown.

Cannot provide more debug info, sorry.

**Comment by brodecva** [comment]
> I believe this is connected to "scope.locked is undefined" problem.
> Usually happens when a user displays a result and changes something (e.g. locks a concept). It seems to > be non-stateless, i.e. when I do this and then go back to taskconfigs and then again head to the result, > the error is thrown.
>
> Cannot provide more debug info, sorry.

These seems reasonable, it never happend for the first result displayed when the application is freshly reloaded.

OK. Thanks, so I'll assign it only to @KataBoku .

**Comment by brodecva** [comment]
>> I believe this is connected to "scope.locked is undefined" problem.
>> Usually happens when a user displays a result and changes something (e.g. locks a concept). It seems to >> be non-stateless, i.e. when I do this and then go back to taskconfigs and then again head to the result, > the error is thrown.
>>

> This seems reasonable, it never happens for the first result displayed when the application is freshly reloaded.

On the other hand it happens even if I do not touch andy feedback mechanisms, only display the result.

**Comment by istvan-satmari** [comment]
"On the other hand it happens even if I do not touch any feedback mechanisms, only display the result."
> Are you sure? Maybe you have not waited long enough. Or maybe you have already visited a result of another task and changed something there. As I mentioned, the scope.locked object seems to be 'stateful', which it shouldn't.

**Comment by brodecva** [comment]
Worked around by switching the order of result pages. Decreasing priority.

**Comment by brodecva** [comment]
@KataBoku fixed it without workaround. Great!
