### ISSUE TITLE
Add guiding text to the free space inside a candidate select box

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#129]
Something like "Click to filter candidates".

**Comment by brodecva** [comment]
Relates to #256 .

**Comment by brodecva** [comment]
@KataBoku solved as a tooltip, as of https://github.com/odalic/odalic-ui/commit/0881208d99be8ed19cfeeb4acc4ff75f4c69ddd3 . It must suffice. Closing.

**Comment by KataBoku** [comment]
I added guide text into select boxes, but it shows only if nothing is chosen.
