### ISSUE TITLE
Handling data cube screen

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#13]
- This issue will be later specified in more detail. It is also questionable whether the functionality is necessary for the first iteration.

**Comment by brodecva** [comment]
Story at https://grips.semantic-web.at/x/dg5OB .

**Comment by brodecva** [comment]
Follow https://github.com/odalic/sti/issues/138 .

**Comment by brodecva** [comment]
@josef-janousek @KataBoku Hi, this is a key missing feature. I rely on you to come up with a passable screen for this. Please cooperate as much as possible and keep me in touch.

**Comment by tomas-knap** [comment]
As we discussed what is missing: 
- To finalize the dialog - naming of tables - dimensions and metrics, combo box attached to the table to which it belongs
- To be able to load feedback to the data cube dialog
- To be able to store feedback from the data cube dialog

Till 6.2. please, as discuss on Friday.

**Comment by tomas-knap** [comment]
Then please assign to @josef-janousek  to test that, @josef-janousek please test that 7.2.
