### ISSUE TITLE
The client wrongly always uses an empty feedback as a  base to compute the sent one

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#134]
The initial feedback after re-run is not set to the current feedback (set before re-run), but to a clean one, which results in forgetting the previous feedback. Always read the feedback first, and then add the changes to it.

This also results in the locks not being in correct state after the re-run.

**Comment by brodecva** [comment]
I have to re-open this one. Does not work for columnAmbiguities, and maybe even other (disambiguations probably). Easy to replicate: run a file, check Skip disambiguation in all cell of this collumn in some header properties dialog, click Reexecute, the selected column has correctly all cells left ambiguous. But when you click the Reexecute again, the feedback sent to server contains no entries in columnAmbiguitites again, not even in disambiguations.

**Comment by istvan-satmari** [comment]
Done, but not my code (correction of @KataBoku 's code), so no guarantees it works as it should.

This also partially solves #175, a certain hack has been removed.
