### ISSUE TITLE
Make 'export to...' buttons disabled after user starts to make feedback

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#135]
"- disabling export tlačidiel po zmene feedbacku zatiaľ nie je nastavený, to je na dlhšie -- ničmenej toto ani nebolo vo waffle.io / emaili, takže to taktne ignorujem pre túto iteráciu

Ano, toto netreba ted, ale prosim udelejte si issue"

**Comment by tomas-knap** [comment]
4th iter, but low prio I would say

**Comment by istvan-satmari** [comment]
Ok, honestly, I have no idea, how to solve this.
Even though it's possibble to put watchers on certain variables that change with user feedback (and disable the buttons at the time of any of the watchers firing), it doesn't work, because the watchers fire at the very beginning, since the corresponding variables change for some reason.

There is a possibility to test with each "fire" whether the current feedback is different from that of the server, but this will have huge performance penalties.

I'm assigning this to @KataBoku , since she may have a better insight into the problem.

Please, @KataBoku , have a look at the code https://github.com/odalic/odalic-ui/blob/exportbts-disable/src/templates/taskresult/view/export/export.js where I tried to deal with the problem. For now setting up of the watchers is disabled; append "()" at the end of the anonymous function from the line 17. 
Thanks.

**Comment by tomas-knap** [comment]
Then I mark as won't fix... Do not lose time on that.

**Comment by brodecva** [comment]
Re-opening as this was something that was picked up by the opponent. We will discuss if anything has changed, or if some quick fix is viable at the next Skype call.

**Comment by istvan-satmari** [comment]
in a way... done.

**Comment by brodecva** [comment]
@istvan-satmari Hi, unfortunately the fix does not work completely. It does detect lock change, but is oblivious to changes in the selected resource, e.g. when I search one and use it.

**Comment by brodecva** [comment]
@istvan-satmari Also it was not wise to commit this one directly to master.

**Comment by istvan-satmari** [comment]
So, more complicated than that it seems... OK, changes "reverted" (commented out).

About the commit, point taken (just me being lazy)

**Comment by istvan-satmari** [comment]
Since I take responsibility for overall KB management, I am leaving this to @KataBoku . 
BTW, there is already a piece of code, which can be used for this and may ease the task for you, @KataBoku .

**Comment by istvan-satmari** [comment]
Done, though I still suspect that bugs can occur. But for the main part, done.

Mind the performance issues, though - not to spend too much time with this, I simply copied the settings of the taskresult at the very beginning and then compare it to the current settings in each angular digest cycle. So you can see what this will do when a large CSV file is being annotated by a user.

Anyway, for me this is as much time as I am willing to put into implementing this feature... (For something so insignificant it is rather hard to 'get it right'.)
