### ISSUE TITLE
UI: Not possible to click on the cell and get to details dialog

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#144]
From Table containing results of classification/disambiguation, I am not able to click on the cell (it was possible before) to get to the "details page", but I have to try to hit tiny icon. 

Solution: When clicking on the cell, I should get to the dialog detail (alternatively I may click the tiny icon)

**Comment by brodecva** [comment]
> From Table containing results of classification/disambiguation, I am not able to click on the cell (it was possible before) to get to the "details page", but I have to try to hit tiny icon.
>
> Solution: When clicking on the cell, I should get to the dialog detail (alternatively I may click the tiny icon)

Hi, well @KataBoku justified this by saying that it is impossible to make the entire cell clickable and allow comfortable selection of the text. Which is hard to argue. The icons could be made larger, I guess.

**Comment by brodecva** [comment]
> Hi, well @KataBoku justified this by saying that it is impossible to make the entire cell clickable and allow comfortable selection of the text at the same time. Which is hard to argue. The icons could be made larger, I guess.

@tomas-knap @KataBoku specifically reminded me that the text selection is needed in order to copy the URIs (as was some of the requirements expressed before in the issues).

**Comment by tomas-knap** [comment]
Ok, yes, won't fix for now.
