### ISSUE TITLE
UI: Border line around the selected cell is really awfull

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#146]
The black line around the selected cell is quite awfull. Also it is awfull that the border line is sometimes partially missing:

![screen shot 2016-11-18 at 14 44 13](https://cloud.githubusercontent.com/assets/3014917/20432073/b2ab1c7a-ad9d-11e6-97a6-3f1c061ea79c.png)

![screen shot 2016-11-18 at 14 44 12](https://cloud.githubusercontent.com/assets/3014917/20432074/b5f2b0a0-ad9d-11e6-997f-837814e5fd88.png)

Maybe it would be nicer to have no line (as it was before), but very light orange background for the selected cell.

**Comment by brodecva** [comment]
Fixed by #211.
