### ISSUE TITLE
Search should not display the alert and load the first result instead into the select box under the input

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#147]
When I search for certain concept, e.g. "Book", click "Find", I got:

![screen shot 2016-11-18 at 14 54 22](https://cloud.githubusercontent.com/assets/3014917/20432362/0d1088d4-ad9f-11e6-8401-a161caf551f6.png)

1) This message has to be removed. 

2) Also the first result should be selected in combo-box. (currently this is not the case)

3) It works very strange - If I try to search once again, it does not work. After a while it starts throwing couple of alerts that there was some issue. 

4) Also when there is some issue while executing search, it should display some error message inside the dialog and does not throw alerts!

**Comment by tomas-knap** [comment]
@brodecva Please discuss with Kata/Istvan who can look on that

**Comment by tomas-knap** [comment]
At least issues 1, 2 should be solvable quickly.

**Comment by brodecva** [comment]
@tomas-knap Agree, I only allowed the alerts under the impression, that proper state visualization (spinners, toast messages) could not be made until the tight deadline (see #132). If you let  @KataBoku some time to work on it, I am sure she will fix 1. and 2. at least.

**Comment by brodecva** [comment]
@KataBoku Hi, please fix 1. and 2. I have moved 3. to a separate issue, which falls under 4th iteration. And 4. is already covered by #132.

**Comment by tomas-knap** [comment]
Yes, please look at points 1) and 2). as part of iteration 3.

**Comment by brodecva** [comment]
>This message has to be removed.

Done.

>Also the first result should be selected in combo-box. (currently this is not the case)

Hardly done. Unfortunately there are some more fundamental issues, that break it after first use (when you add a selected search entity and attempt to find another term, the first result entry is an empty line for some reason).

> It works very strange - If I try to search once again, it does not work. After a while it starts throwing couple of alerts that there was some issue.

Yep.

>  Also when there is some issue while executing search, it should display some error message inside the dialog and does not throw alerts!

A spinner was introduced which should at least partially visualize the progress and possible success. Proper error handling and reporting is left to solve later.

**Comment by tomas-knap** [comment]
Missing to solve: 
- there are still some issues showing first result in the combo box
- it works very strange - If I try to search once again, it does not work. After a while it starts throwing couple of alerts that there was some issue.

Point 4 above is solved in #132.

**Comment by istvan-satmari** [comment]
Postponed, until the reporting service is improved.
For now just throw an exception.

**Comment by tomas-knap** [comment]
@KataBoku What is the status? THe idea is to solve: 
- there are still some issues showing first result in the combo box
- it works very strange - If I try to search once again, it does not work. After a while it starts throwing couple of alerts that there was some issue.

**Comment by brodecva** [comment]
Closed by #210 .
