### ISSUE TITLE
Repeated search fails and behaves unreliably

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#148]
It works very strange - If I try to search once again, it does not work. After a while it starts throwing couple of alerts that there was some issue.

Solution: Do not throw alerts, just display errors in the dialog! It even happens to me that I close the dialog with the classification detail and start a new task and then I got alert that there was search issue!

**Comment by tomas-knap** [comment]
@brodecva I would suggest that @istvan-satmari will examine that - as this could be very tricky.

**Comment by brodecva** [comment]
@KataBoku I have added the stamping support as you wanted. Just send the requests to a URL with a "stamp" parameter added (its value can be a string of yours choosing) and the string will be sent back to you in a response alongside the payload under a string containing field called "stamp" in the wrapping object.

**Comment by tomas-knap** [comment]
@KataBoku Please report the status - as this was solved as part of the search branch, what is the status?
