### ISSUE TITLE
UI: Search should be available for all knowledge bases

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#150]
In UI, search component should be available for all knowledge bases, as in: 
https://grips.semantic-web.at/display/ADEQ/Scenario+4b+Customizing+classification+class+-+selecting+different+non-suggested+primary+class+for+the+column+classification

Current situation - there is only one search component. 

Please prepare it reasonably, so that search component is aligned with the rest of controls in the dialog.

**Comment by brodecva** [comment]
Done together with #195 .
