### ISSUE TITLE
UI: Diagram with classification/disambiguation details is awful

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#151]
When I open detail diagram for proposing classes, I got: 

![screen shot 2016-11-18 at 14 32 59](https://cloud.githubusercontent.com/assets/3014917/20431761/0b845e3a-ad9c-11e6-9264-19c2063c334c.png)

1) Why is here the "P" in German DBpedia? Probably some remnant of "Pick one" - has to be removed

2) The controls are not anyhow aligned - Search label/text box should be aligned (start) on the left - as the other labels/text boxes 

3) Search text box should have the same hight as the combo box 

4) Proposal button should have the same size as other buttons and same style

**Comment by brodecva** [comment]
> Diagram with classification/disambiguation details is **awful**

Come on, @tomas-knap . Awful? The "diagram with classification/disambiguation details" has its feelings too. :-)

Otherwise not doubts about that, I gave it a pass under the strict deadline, but as long as there is some time, this should be fixed for the 3rd iteration. Just please make it clear, how much time do we have to do so.

**Comment by brodecva** [comment]
> Why is here the "P" in German DBpedia? Probably some remnant of "Pick one" - has to be removed

Removed.

> The controls are not anyhow aligned - Search label/text box should be aligned (start) on the left - as the other labels/text boxes

Discussed with @KataBoku , she was adamant that this is really to much work to do, unless a refactoring is done first. Virtually all others divs in the same frame would have to be fixed.

> Search text box should have the same hight as the combo box

Fixed.

> Proposal button should have the same size as other buttons and same style

Size - yes, style - unfortunately not so much. The Bootstrap in the UI uses some kind of very rigid layout, that makes it rather complicated: if I made the button of the same style as the others, I would have to recompute its position. Sorry about that. @KataBoku will fix it later.

**Comment by tomas-knap** [comment]
Missing: 
- align controls (when @istvan-satmari  is done with refactoring)
- align the style/size of buttons

**Comment by istvan-satmari** [comment]
Done though I have a hard time believing visuals are worh prioritizing. 

Especially when I get a continuous exception "NS_ERROR_FAILURE" when locking an entity, switching to another view, and switching back.
Note that an exception that gets thrown every ~0.01 seconds actually DOES slow an engine. A lot.
