### ISSUE TITLE
UI: Propose may add the same label multiple times!

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#153]
When proposing new class (for the column headers) it must not add the same resource more times:

Current situation: I may click on OK in propose dialog couple of time -> as a result, the same label appears multiple times!

![screen shot 2016-11-18 at 15 37 01](https://cloud.githubusercontent.com/assets/3014917/20433724/3f8afcf8-ada5-11e6-9af6-82cf297277d7.png)

Solution: It must be checked that the label was not already added!!

**Comment by tomas-knap** [comment]
Server will not allow to add the same concept under the sam e URL. Check with the server

**Comment by brodecva** [comment]
Fixed and ready to be pushed after @KataBoku adds error message display.

**Comment by tomas-knap** [comment]
Please point to the commit where it was fixed

**Comment by brodecva** [comment]
This seems to be resolved in the https://github.com/odalic/odalic-ui/commit/c836f29858eadc9c6747fa629cd68b29368fe2e5 . I will close this one when my comments to the associated pull request are reflected.

**Comment by brodecva** [comment]
> This seems to be resolved in the https://github.com/odalic/odalic-ui/commit/c836f29858eadc9c6747fa629cd68b29368fe2e5 . I will close this one when my comments to the associated pull request are reflected.

Taking it back. The issues I have are not that major. I will instead create a separate issue for them.
