### ISSUE TITLE
UI: Propose - remove strange label for "uri prefix"

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#156]
What is this "url zmenit podle ceho"?? This must be adjusted. It should take, as we discussed, the prefix from the setting of the knowledge base (from a file)

![screen shot 2016-11-18 at 15 53 07](https://cloud.githubusercontent.com/assets/3014917/20434277/5f577320-ada7-11e6-8c95-41551e575671.png)

**Comment by brodecva** [comment]
Agree, the label should specifically say something akin "URI suffix" (refer to the GRIPs for details), because the prefix is derived from the targeted base configuration.

**Comment by brodecva** [comment]
Fixed.
