### ISSUE TITLE
UI: Re-execute: Propose class is not retained but proposed entity is!

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#157]
To reproduce: Run odalic on top of book1.csv. 
Propose new class for column header (Author). Propose new entity for the cell value (Steven Ericson), in a similar way as below: 

![screen shot 2016-11-18 at 15 52 06](https://cloud.githubusercontent.com/assets/3014917/20434586/b2f235a0-ada8-11e6-91c4-b91315badc7e.png)

In both cases the cell values are correctly locked. 

When I click "reexecute" I got: 

![screen shot 2016-11-18 at 15 52 57](https://cloud.githubusercontent.com/assets/3014917/20434591/bd31c260-ada8-11e6-9839-3f907adb8a51.png)

As you can see, proposed resource for entity disambiguation is retained, but is LOST for class (column header)

Note: As I was testing that, the proposed concepts were not stored to the KB, they were just added by UI

It is an issue of UI, because API provides both previously proposed resources.

**Comment by brodecva** [comment]
> It is an issue of UI, because API provides both previously proposed resources.

Not necessarily. See  https://github.com/odalic/sti/issues/202 .
