### ISSUE TITLE
UI: Relations - canvas - nodes may be partially hidden

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#158]
Currently, when I move the node to the end of the canvas, it looks as follows: 

![screen shot 2016-11-18 at 16 34 19](https://cloud.githubusercontent.com/assets/3014917/20435628/160d2150-adad-11e6-9ac5-4f0a91bc1222.png)

Solution: Do not allow to move node that much to the end - it should be always fully visible
Note: You may also increase a bit the canvas

**Comment by brodecva** [comment]
Agree, this is annoying. The canvas could be also enlarged for sure.

**Comment by istvan-satmari** [comment]
Done. As for the canvas enlargement, I am not sure what is the 'right' size (as you can see people have different displays and the canvas may not fit on their screen.)
If you feel the current settings is not OK, lookup the file "graphvis/node.js", lines 32-35:

var svg = d3.select(iElement.get(0).childNodes[2])
                    .append('svg')
                    .attr('width', 1200)
                    .attr('height', 550);

The width and height may be easily changed.
Or just leave a suggestion for a specific value here. 
Thanks.

**Comment by tomas-knap** [comment]
Thanks, if some enlargement is needed, we know where to adjust that
