### ISSUE TITLE
UI Search: Does not work for relations

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#159]
_From @tomas-knap on November 18, 2016 15:26_

Steps to reproduce: Go to relations tab, create new relation, search for something. 
Although the dialog says "result is available", there is nothing displayed!

_Copied from original issue: odalic/sti#218_

**Comment by istvan-satmari** [comment]
No dialog showing up, just the combobox gets filled with found concepts. (Or nothing, if the searched expression is not found.)
You need to be more specific.

**Comment by istvan-satmari** [comment]
Seems OK, but keep an eye on it.
