### ISSUE TITLE
Propose: Showing class for entity (object of the real world), do not allow to propose entity without class

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#162]
Change motivated by: https://github.com/odalic/sti/issues/227

1) There is a need for field (read only field), which contains class for that column (from primary KB)

2) If there is no class for that column (from primary kb), it must not be possible to create/propose such disambiguation.

**Comment by tomas-knap** [comment]
Note: I expect that point 3 from the task description could be realized a bit later (on the server side), but Kata may already prepare the checkbox now.

**Comment by brodecva** [comment]
@KataBoku I commented on the associated pull request. The issues I had with it must be dealt with before the request can be merged.

**Comment by tomas-knap** [comment]
@KataBoku This is already done, right?

**Comment by tomas-knap** [comment]
@KataBoku will remove cross from the alert, then solved.

**Comment by brodecva** [comment]
Closed by #220 .
