### ISSUE TITLE
UI Propose: Only one classifying concept per KB

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#163]
Due to limitation of the algorithm (see https://github.com/odalic/sti/issues/202), when new class is proposed for the column header, it has to replace the existing from the same KB. So it is allowed to have only one classification for each KB. 

So the behavior should be the same as in case of proposing entities disambiguating cell value, where also only one selected disambiguation per KB is allowed

**Comment by tomas-knap** [comment]
Does not work, I was currently testing develop - commit 8fec49023d51674fa47d21bc5ebd002bf7ac640f
and I was able to add more classes: 

![screen shot 2016-12-13 at 18 02 07](https://cloud.githubusercontent.com/assets/3014917/21150228/8526f3b2-c15e-11e6-95f8-1d379c36e1d2.png)

**Comment by brodecva** [comment]
Not working. When you propose a second class for a header, it gladly allows it to add it to the selection. As of https://github.com/odalic/odalic-ui/commit/a1e652df81264f006a4a6eec878c77927f6fb7fc .

**Comment by brodecva** [comment]
Tag as in-test and assign to me, @KataBoku , when the solution to #153 is pushed (which should arguably fix the reported problems by me and @tomas-knap ). I will check tomorrow.
