### ISSUE TITLE
Icon text should not be longer then the button

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#165]
Start from beginning flows out from the button: 
<img width="748" alt="screen shot 2016-11-27 at 17 18 50" src="https://cloud.githubusercontent.com/assets/3014917/20649700/a265879a-b4c5-11e6-8c19-27d5234afb4c.png">

T

**Comment by brodecva** [comment]
@tomas-knap This is relatively minor thing, no reason to postpone it until the 5th iteration.

**Comment by istvan-satmari** [comment]
I decided to remove the button completely, since it had no functionality attached.
BTW, the 'overflow' did not show on my browser until I zoomed up to cca 150%. What screen resolution do you have? What will our average user have? (It will never work for all types of screens, obviously.)
