### ISSUE TITLE
<ui-select> corrupts result object after reinsertion of an entity (relations)

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#167]
See the attached picture.
![bug](https://cloud.githubusercontent.com/assets/17832462/20672956/66effab0-b583-11e6-9240-1c7d5bd0dadc.png)

**Comment by tomas-knap** [comment]
Is that valid for all propose activities - also when proposing classes and disambiguated entityes - or is it valid (occurs) only when relations are proposed?
