### ISSUE TITLE
Add API for properties proposing (for relations)

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#170]
Similar to proposing resources and classes, please help us get together what is necessary (no sketches needed). I assume domain and range might come handy, what else? Super-property?

**Comment by tomas-knap** [comment]
The user should not define the domains/ranges manually, but should be derived from the concepts from primary KB classifying the subject/object of the relation. "Subproperty of" should work in the same way as subclass of for concepts classifying the column - so it should be possible to search for super properties. 

Can be done also in steps - first at least be able to propose new relations (for sure 4.iter) and then adding domain/ranges and subproperties (could be 5th iter)
