### ISSUE TITLE
Icons in cell values are differently positioned depending on the size of the column

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#171]
The icons for proposing/viewing detail/locking are sometimes on the same line as column title, sometimes not. Sometimes they are on the same line, sometimes not (look at the column year).

![screen shot 2016-11-30 at 16 27 05](https://cloud.githubusercontent.com/assets/3014917/20758392/f24f6356-b719-11e6-9555-bff1f37e4f91.png)

Solution: 

- the icons should be always on the same position - top right corner, the same line as column title
 - it should never happen that some icons are on the first line, some on the other

**Comment by brodecva** [comment]
@KataBoku @tomas-knap Simply setting a minimum column width to such value, that at least the icons fit, might solve it.

**Comment by tomas-knap** [comment]
the problem is that you do not know how long is the column label. Anyway, it should behave in a way that the icons are always together in the right top corner
