### ISSUE TITLE
Labels of nodes in the relation graph not nicely depicted

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#172]
File: https://github.com/odalic/sti/files/622142/STMK_2012_LIVEBIRTHS-10lines.csv.zip 

![screen shot 2016-11-30 at 16 31 54](https://cloud.githubusercontent.com/assets/3014917/20758584/9c90adb6-b71a-11e6-917a-d410aae2a7a3.png)

Issues: 
- it is not nice when the labels do not fit into the nodes - e.g. LIVEBIRTHS
- DIS...AME - standing for DISTRICT_NAME - that is really not nice! 

Suggested solution: I would suggest to have a bit bigger nodes. If the labels do not squeeze, I would suggest to put "..." at the end (rather then to the middle). Labels may occupy more rows (if multiword and if easy to implement).

**Comment by brodecva** [comment]
I would also try to make the font smaller.

**Comment by tomas-knap** [comment]
What we discussed: 
- Smaller font, so that you can show more
- Do not show dots in the middle, but rather just the beginning
- Show whole label in the tooltips - https://github.com/odalic/odalic-ui/issues/173

**Comment by tomas-knap** [comment]
Font decrease (at least) in iter 4, rest in iter 5
