### ISSUE TITLE
Make the proposed resource for disambiguation an instance of the column class

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#177]
@tomas-knap:
> In case entity (not class/predicate) is proposed, it should be automatically "instance of" of the real class from the primary knowledge base which is used for classifying the column (and not the pre-configured root class).
> 
> If the class is not known (there is no classification from the primary knowledge base), such propose should fail with a message (it is necessary to first select/propose class for the column from the primary knowledge base).
>
> For class classificaiton, do not define the triple "X subClassOf Thing", as this is valid by default for all classes, there is no need to explicitly materialize that.

**Comment by tomas-knap** [comment]
So if I understand it correctly, Kata has to feed the backend service with the class the disambiguated entity should be instance of - but this should be easy, as long as the classification for the column is known, right?

**Comment by brodecva** [comment]
> So if I understand it correctly, Kata has to feed the backend service with the class the disambiguated entity should be instance of - but this should be easy, as long as the classification for the column is known, right?

Right.

**Comment by brodecva** [comment]
Closed by #220 .
