### ISSUE TITLE
File upload does not show uploaded files

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#179]
When using a different base URL, i.e. instead of http://localhost:8080/odalic/ I use http://localhost:8080/ (this is due to a use of a different IDE - IntelliJ IDEA), the REST requests seem to be OK. However, I get an exception when uploading a file.

This seems to be an error of the UI, not the server.

**Comment by brodecva** [comment]
@istvan-satmari Is this not related to https://github.com/odalic/sti/issues/155 ?

**Comment by istvan-satmari** [comment]
The error seems to be on my side, but I'll keep an eye on this

**Comment by istvan-satmari** [comment]
Makes no sense to leave this open; this is a personal issue with Idea IDE. Closed.
