### ISSUE TITLE
Task name cannot contain spaces

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#18]
When the name of the task contains space, it throws exception. 

Solution: Task name must support also spaces

Steps to reproduce:
- Create new task, specify as task name "my task"
- Select some csv
- Click "Create"

As a result, error is shown: 

<img width="1284" alt="screen shot 2016-07-11 at 15 57 21" src="https://cloud.githubusercontent.com/assets/3014917/16733143/93b18b02-4780-11e6-9381-fb33cd2411a2.png">

**Comment by brodecva** [comment]
This issue was moved to odalic/sti#88
