### ISSUE TITLE
Don't print stuff to console if no longer needed

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#180]
I get it that when programming and debugging your code, printing out 'stuff' to console is useful.
But if a branch is merged, it usually means your code works and there is no more need for the leftover "console.log" statements. Please, remove them.

It is a different thing when having a server that needs to log all its actions, but JS cannot do something like that.

**Comment by brodecva** [comment]
> I get it that when programming and debugging your code, printing out 'stuff' to console is useful.
But if a branch is merged, it usually means your code works and there is no more need for the leftover "console.log" statements. Please, remove them.

> It is a different thing when having a server that needs to log all its actions, but JS cannot do something like that.

Hi, I would not be so harsh. Not all errors are caught when merging, so logging might help even much later.

Also the logging does not hurt, common user does not see it.

But all this of course means that the logging has a proper form.

I would instead suggest to use some logging library that allows you to set levels of the messages and optionally turn on/turn off the message logging depending on its level.
