### ISSUE TITLE
Implement paging

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#184]

**Comment by istvan-satmari** [comment]
- taskresult
- taskconfig
Presumably can be done via ui-bootstrap; need to do some research first.

**Comment by istvan-satmari** [comment]
Seems to be... finished? It works for me...
If you want to test it, I recommend searching for "perPage" variable and set it to 1 (so only 1 item is displayed per 'page'; so you don't have to create large amount of tasks / files).

Limits are as follows:
- 5 lines for taskresult (templates/taskresult/controller.js, line 172)
- 10 files per page in filelist (.../controller.js, line 22)
- 10 tasks per page in taskconfigs (.../controller.js, line 25)

**Comment by tomas-knap** [comment]
There is probably some issue. The following is result of class/disamb with big pages (there is just one) - see the line with value "Benesov" and proper annotation. 

<img width="1425" alt="screen shot 2017-01-20 at 18 26 56" src="https://cloud.githubusercontent.com/assets/3014917/22158773/35ace2e4-df3e-11e6-885d-eafe6445e161.png">

If I turn on pagination (5 per page), then the content of the original CSV file is OK, but wrong disambiguation labels are attached to the cell values sometimes  (see e.g. the "Benesov" cell value again and the cell values below "Benesov" cell value):

<img width="1440" alt="screen shot 2017-01-20 at 18 22 53" src="https://cloud.githubusercontent.com/assets/3014917/22158781/3c84cdd4-df3e-11e6-9c4a-ccab92cbdc13.png">

**Comment by tomas-knap** [comment]
Note: Tested latest develop, but a bit older backend:   commit e4097d0ac28f7d0ad61ef335dc01726cf92fa348

But should not play a role I guess?

**Comment by tomas-knap** [comment]
Tested on : http://www.coi.cz/userdata/files/dokumenty-ke-stazeni/open-data/kontroly.csv
First 20 lines, separators ",", escape char "\", knowledge base - see the config here:
[DBPediaSearch.properties-RUIAN.zip](https://github.com/odalic/odalic-ui/files/720089/DBPediaSearch.properties-RUIAN.zip)

**Comment by istvan-satmari** [comment]
"But should not play a role I guess?" - no; it's independent from server.
I'll look into it.

**Comment by istvan-satmari** [comment]
Done.
Cells are index-dependent (i.e. dependent on information, on which row they are located). Resolved by recomputing the index.
