### ISSUE TITLE
Loading of result is slow

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#185]

**Comment by tomas-knap** [comment]
To be more precise, slow is the loading of the screen with annotations for classes/disamb. (the first Step of the result)

**Comment by brodecva** [comment]
@istvan-satmari 's description from a duplicate issue:
> ng-switch in taskresult template inserts/removes subtrees in DOM => reloading the taskresult table takes therefore longer than it should.
>
> solution: create an alternative directive to the built-in one 'ng-switch'.

**Comment by istvan-satmari** [comment]
Won't fix.

Reason: Though the directive was successfully implemented, the graphvis component is suddenly bugg-y (it counts on being destroyed from DOM after not being used anymore). Additionally Firefox (browser specific bug) throws NS_ERROR_FAILURE exception which causes it to freeze. So basically "too much work for little gain".
