### ISSUE TITLE
Task creation - specifying source is not intuitive

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#19]
Currently, the layout of task creation is as follows:

<img width="1212" alt="screen shot 2016-07-11 at 16 05 32" src="https://cloud.githubusercontent.com/assets/3014917/16733409/c022c4ca-4781-11e6-8e7f-820a7ca70f58.png">

 This is rather unintuitive. User has to fill identifier, then return back to select it...
 It has to be changed as depicted in user story: 
https://grips.semantic-web.at/display/ADEQ/Story%3A+User+can+configure+source+of+the+task

Main changes; Identifier only for newly uploaded data, identifier pre-filled.

**Comment by brodecva** [comment]
Some added notes (concerning the current state and the story):
- Do not forget to switch the position of the input for choosing existing files and the parts for uploading a new one.
- When no identifier provided, derive it automatically, from the file name (ideally immediately after specifying the file -DO NOT FORGET TO SANITIZE THE NAME TO MAKE IT A VALID PART OF URL). The user can change the identifier if needed, then.
- Make all the error messages more user friendly. Either by adopting the error messages from API replies, or on your own, when the action does not mandate any API request and reply.

**Comment by brodecva** [comment]
Also:
- After successful Upload, the selected file name next to the Browse button should disappear.
