### ISSUE TITLE
UI - results - Labels for concept classifying columns not depicted?

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#190]
When I run Odalic agains ADEQUATe KB, in case of disambiguation, UI properly shows labels (see below, URI contains UUID, but there is nice label). But in case of classificiation, label is not obtained and UUID is used. Why? 

![screen shot 2016-12-13 at 20 41 07](https://cloud.githubusercontent.com/assets/3014917/21156307/b291a880-c175-11e6-9df9-a70d2f2ae7d0.png)

Solution: It should also take the label of the concept being suggested for classification. 

@KataBoku did you encounter that as well?

**Comment by tomas-knap** [comment]
So it seems that the problem is that the header column is not able to display labels contained within skos:prefLabel property (although such property may be defined in the config file for the KB - in the enums, but probably applies only to disambiguated entities?)

For disambiguated entities it works correctly.

**Comment by brodecva** [comment]
This issue was moved to odalic/sti#254
