### ISSUE TITLE
Send file format parameter (delimiter, character set,...) to server when specifying a file

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#191]
For now put it on hold, I will notify you when the server part is ready and provide you with the API description.

**Comment by brodecva** [comment]
- The available API calls are described in the latest REST API specification. Please note that in case of a file uploaded from computer, a separate subsequent API call must be made in order to set the right format. For remote files the format specification can be a part of the sent specifying object.

- The File settings section should be made a part of the Input file section, so it is clear that the file settings are read during the upload, not during task creation (Although you could implement it like that, I do not recommend it: Consider a case, when you upload a file, but do not create the task in the end. The file remains available and the user assumes it has the correct format set, which would not be true.

- The line separators are not a part of the format (at least for now), because the used library detects them automatically. For the other values in the format object, design a suitable set of form controls (discuss with @josef-janousek which of them are necessary, those which are not, set to a reasonable value and do not put in the form). Consider providing the list of supported (see API specs) character sets in a select box, with the common sets (UTF-8, US ASCII, German and Eastern Europe ones) at the top. Allow to specify the custom characters.

Contact me, if something is not clear.

**Comment by tomas-knap** [comment]
Yes, please provide the most typical encodings in the combo-box. Others may be defined if needed.

**Comment by istvan-satmari** [comment]
It seems to me that a separate screen specially for file handling should be made.
The question is, why was it included as a subpart of the task creation in the first place? I don't get it.

This seems like a 'bigger deal', some (non-trivial) time will need to be spent on this. Since the REST API supports file upload/delete/...etc, it should probably be reflected in the GUI. Ideas about the particular issue?

**Comment by tomas-knap** [comment]
I think that the typical workflow is as follows: 
1) User uploads new file
2) We automatically prefill certain attributes, such as line endings/encoding (depending on how smart we are)
3) User may customize that then. 
4) User may save that. 

An alternative workflow is that:
1) User selects existing file
2) User must see the currently saved configuration (line endings/..) for that file
3) User may customize that then
4) User may save that.

So we have two approaches to realize that: 

1) Move the File settings section (encoding/line endings/delimiters) to a different dialog and add "Configure" button e.g. next to "Selected file" combo box, under the "Upload" button. In that extra dialog, provide also "Save" button to save the config. The advantage is that we have the "Save" button, disadvantage is that the settings are not visible directly from the main dialog.
2) Leave it as it is, but merge file settings with input file section of the config. When file is uploaded, certain options, such as e.g. line endings, may be prefilled automatically (at least in the future), the rest can be specified by the user. If the user selected existing file, the settings are prefilled based on what is saved by us (shared among users) **Then I would suggest to add there an extra save button "Save file configuration"** (this is not completely conceptual as we have dialog, for which certain fields may be saved separately). When user does not click on that "save file configuration" but does click on create and run/create - some message should appear asking whether file configuration should be saved.

I prefer Option 1, as the flow is then more easily understandable - 1) user knows he must save the configuration of a file if changes are done, 2) Also user knows that he should first selects/upload file and then, if needed, may see/change further settings.

So I would just put the "file settings" to a separate dialog with an extra save button.

**Comment by istvan-satmari** [comment]
I implemented the solution @tomas-knap  proposed, seems like we had the similar idea about this one.
So the solution is to put it simply, a separate modal window which handles the file configuration. 
Done; already in develop.
