### ISSUE TITLE
Add limit option to task configuration

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#193]
Basically a combination of check box (when ticked, then the input will be cut after certain number of rows before each processing) and an element allowing to choose the number of lines (this is optional, certain number of rows can be agreed upon).
On hold until the server capability is implemented.

**Comment by brodecva** [comment]
The API option to do that is now available, see specs. The limit will affect only the processed input (and the base for the feedback), not the uploaded files (and the remote ones even less so).

**Comment by istvan-satmari** [comment]
Will be implemented in createnewtask screen since any task's configuration can be easily changed. It is more logical this way and less work.
