### ISSUE TITLE
Too long URLs causing troubles with the combo box component in annotation detail

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#194]
Testing Odalic agains ADEQUATe KB. Too long URIs causes to run out of the dialog, which is not nice.

![screen shot 2016-12-14 at 17 26 27](https://cloud.githubusercontent.com/assets/3014917/21190649/d1c36434-c222-11e6-8f67-609706d1a2e9.png)

Quick Solution: I would suggest to make the dialog a bit wider for now, so that we do not have such issues. Later on, this should be mitigated by using prefixes. But better solution is preferred, see below. 

Better Solution: It should behave in the responsive way - so if the user changes resolution (see below), it should be able to cope with that - e.g. the component should be able to automatically adjust the size of the displayed portion of the URI or split the URI into more lines. For sure it is not the best idea to just display everything on one line without of the respect to the size of the dialog. 

![screen shot 2016-12-14 at 17 33 59](https://cloud.githubusercontent.com/assets/3014917/21190904/c281b68c-c223-11e6-857c-8e97133927ff.png)

**Comment by istvan-satmari** [comment]
This was a little bit tricky, since UI-SelectBox component does not provide any method to deal with this (AFAIK). Hopefully solved, though.
