### ISSUE TITLE
Automatically removing annotations for the cell values with the same content as the one for which annotation was removed

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#195]
Suppose that the Step 1 shows the following: 

![screen shot 2016-12-15 at 17 05 52](https://cloud.githubusercontent.com/assets/3014917/21231585/18a79624-c2e9-11e6-8325-96955b25674e.png)

I decide to remove certain disambiguations as follows (as a result, the cell is also locked) - see the second column, second row:

![screen shot 2016-12-15 at 17 06 08](https://cloud.githubusercontent.com/assets/3014917/21231589/1c83211e-c2e9-11e6-8c8a-16194860723c.png)

When I now re-execute the algorithm it looks as follows: 

![screen shot 2016-12-15 at 17 12 02](https://cloud.githubusercontent.com/assets/3014917/21231740/a0b56258-c2e9-11e6-91cc-b0c8aa42723b.png)

So the algorithm (that was smarter I expected ;-) removed also the same disambiguations for the cells with the same content as the one I removed and locked manually - so not just for the second row of the second column, but for the whole second column. But the "locker" icon remains "unlocked" for the other rows - so it is locked only for the second row, second column. 

Is that what is expected? Maybe some clarification would be good!

**Comment by brodecva** [comment]
@tomas-knap I see nothing that strange about it. Disambiguation of cells in a column is intertwined. When you manually prevented disambiguation of one of them, it affected the way the algorithm automatically disambiguated the others. I am afraid it would be really hard to lock the others in such case, because the choices of the algorithm might to opaque for that.
I will assign to @josef-janousek , who has done the excellent job of providing the feedback to the algorithm, and who should be familiar with the algorithm decisions.

**Comment by tomas-knap** [comment]
Yes, I assigned on me on purpose, I think it is OK, but I was just a bit confused at the beginning, so would like to think about that ;-) So reassigning on myself, do not spend time on that for now

**Comment by tomas-knap** [comment]
@josef-janousek Maybe if you can just write your opinion on that

**Comment by brodecva** [comment]
@josef-janousek replay (in Czech) from a Skype conversation:
> Ahoj, ohledně toho issue https://github.com/odalic/odalic-ui/issues/195 : tato funkcionalita "přeskakování řádků" už byla v TM+ implementována od Ziqiho (parametr skipRows v metodě pro disambiguaci), jen zatím nebyla využívána, nyní jsem ji jen použil, takže její podrobnější chování jsem nezkoumal a asi by to byla spíše otázka pro Ziqiho, jak to konkrétně funguje...

**Comment by tomas-knap** [comment]
Od Pepy: přeskakování je testováno v těchto místech: https://github.com/odalic/sti/blob/develop/sti-main/src/main/java/uk/ac/shef/dcs/sti/core/algorithm/tmp/LEARNINGPreliminaryDisamb.java#L62 , jestli a kde to má pak další vliv, to už nevím

**Comment by tomas-knap** [comment]
I would suggest to close that for now. It behaves reasonably.

**Comment by tomas-knap** [comment]
@brodecva Please re-open if you think it requires more attention
