### ISSUE TITLE
Differentiate columns with no annotations and ignored columns

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#196]
There is no difference between the columns which were not disambiguate because they were ignored by default (e.g. becase they were not considered as named entities) and the columns which were disambiguated, but no disambiguation found. 

E.g. below, the district code has no annotations because it is not a named entity column, but the NUTS2 column has no annotations because I explicitely removed disambiguations, and NUTS3 has no annotations because there were no disambiguations in the target KB

![screen shot 2016-12-15 at 17 14 07](https://cloud.githubusercontent.com/assets/3014917/21232080/b9d93b82-c2ea-11e6-9bb5-ea9971ad986a.png)

Solution: Emphasize somehow which column is considered as non-named entity and ignored or in more general emphasize somehow the ignored columns to differentiate them from columns for which there is no annotation.

**Comment by brodecva** [comment]
@tomas-knap OK. I will discuss it with @KataBoku and @istvan-satmari .

**Comment by brodecva** [comment]
@josef-janousek Could you propose a way to extend the Result first with the information about whether the columns is not NE, or if just no disambiguations were found?

**Comment by brodecva** [comment]
> @josef-janousek Could you propose a way to extend the Result first with the information about whether the columns is not NE, or if just no disambiguations were found?

I mean, how to get it from the algorithm result or during its processing.

**Comment by josef-janousek** [comment]
The server part is implemented in https://github.com/odalic/sti/pull/371 . ColumnProcessingAnnotation can contain three types of column processing: NAMED_ENTITY , NON_NAMED_ENTITY or IGNORED . NAMED_ENTITY is default variant and does not have to be emphasized, the other variants (NON_NAMED_ENTITY and IGNORED) are special cases when the column is not disambiguated (and so classified) and should be somehow emphasized in the header (some styling - @tomas-knap could provide more info about styling options).

**Comment by tomas-knap** [comment]
Next steps: Please test and merge odalic/sti#371
Please assign UI team

2 Ideas: 
1) We can just change a bit the background of the column - I would suggest to change only the background of the header cell. 
2) Add non-clickable icon to each column - 3 different icons - for named entities columns, non-named entities, ignored. 

Approach 2) Would be maybe prefered as we play quite a lot with background colors (every second row, kb suggestions)

**Comment by brodecva** [comment]
@tomas-knap Or maybe change the font maybe, all non-ignored to be bold, plus the italics for non named entity?

**Comment by brodecva** [comment]
@KataBoku  See REST spec for the change in result format.

**Comment by tomas-knap** [comment]
I am a bit worried that changing font would not look good as it would look too chaotic. Different colors, different fonts, ..

**Comment by tomas-knap** [comment]
But you can try that - to have bold everything which was considred (named entities and non-named entities) and also italics e..g for non-named entities. This is probably easiest

**Comment by brodecva** [comment]
Well, this is embarassing. It took @KataBoku to notice that we did not defined how the display should behave should two bases differ in their assessment of a column. Naturally fonts change of the column label read from the input is off the table in such cases, and in general.

We discussed with @KataBoku two solutions: either move this information to the detail of particular column (which is already pretty cluttered, and the user must open the detail first), or just show it in tool tip as a title content when hovering over header as a textual information for each base (obvious downsides, but we already use these to display the full name of a column in a relation in the graph, so no big deal, I guess).

We chose the latter option. Please, @tomas-knap , let us know, in the case it is not OK, as soon as possible, ideally with alternative proposal.

**Comment by tomas-knap** [comment]
Well, is it really knowledge base dependent? I mean to differentiate between named entities and non-named entities columns? Also ignore is valid for all kb, right?

**Comment by tomas-knap** [comment]
Lets discuss that on the meeting **before merging**

**Comment by tomas-knap** [comment]
Only for primary KB. When done assign to @tomas-knap, I will adjust label
