### ISSUE TITLE
Propose button inside the cell properties modal dialog does nothing

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#198]
As of https://github.com/odalic/odalic-ui/commit/a1e652df81264f006a4a6eec878c77927f6fb7fc .

**Comment by istvan-satmari** [comment]
Done - this was a scoping problem due to solving the issue concerning modal visuals.
Though corrected, the modal after "Proposal" button is clicked, is displayed behind the main one. I believe this should be corrected, but I have no idea why it happens. Tagging @KataBoku for resolving.
