### ISSUE TITLE
Propose dialog stays open after clicking OK

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#199]
There is no point to leave it open. It is much more common to add only one proposal per cell or column.

**Comment by brodecva** [comment]
@KataBoku @istvan-satmari Please decide on who will fix this. @KataBoku might be more suitable actually, because she has just finished related issues. On the other hand she is occupied by finalization of the search issues.

**Comment by istvan-satmari** [comment]
I'll take it
