### ISSUE TITLE
Template: Task history

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#2]
- POSTPONED
- HTML template for task history
- Include pagination only as html elements without any functionality
- Include filtering and sorting only as html elements without any functionality
- Only HTML elements should be part of the task. If JavaScript has to be used, then only for initializing Angular controllers.
- Consider and include a validation of the user input where applicable. (Use ONLY html attributes. Extend with Angular directives, if needed.)

**Comment by brodecva** [comment]
Hi, as this is not an essential (if I understand it correctly) for the 1st iteration (the more so for the presentation at June 20th), please postpone this issue, unless you have some valid reasons to not do so.

**Comment by istvan-satmari** [comment]
Very well.
