### ISSUE TITLE
Unappealing red text for error messages in the proposal dialogue

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#201]
The propose error messages must use the same, nice style as the error message displayed when the user forgets to select a file. The red text is not that appealing. Especially considering that the confirmation message is rendered as usual.

**Comment by tomas-knap** [comment]
Follow-up of #200

**Comment by KataBoku** [comment]
Išty solved this issue with his error-msg directive

**Comment by tomas-knap** [comment]
@brodecva Please close that when merged to develop

**Comment by tomas-knap** [comment]
@brodecva what us the status?

**Comment by brodecva** [comment]
@tomas-knap Yes. This is finished. But I was still not satisfied with the look of it, so there is a #218 , which should adjust the colour schema and the shape. This is assigned to @istvan-satmari .
