### ISSUE TITLE
User can fill the cell resource proposal form even when it is not possible to send it

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#202]
The message that the column is not classified, and therefore the user cannot propose the cell resource, is not standing out enough among the other pre-displayed messages. So the user happily continues to fill the form only to realize that the last message will not go away and he or she has to close the dialogue (losing all the input in the process) first, fix the classification and then start the proposal again. This is frustrating. Either just show this error message up front without even opening the dialogue, or allow to propose classification from the cell proposal dialogue.

**Comment by tomas-knap** [comment]
Follow-up of #200
