### ISSUE TITLE
Upfront display of error messages in proposal dialogue might scare the user

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#203]
I would strongly prefer the combination of displaying the error messages only when the input is wrong when the user clicks OK and somehow indicating which fields are obligatory vs. displaying the error messages up front, even when the user has done nothing yet. But this is not mandatory as long as the following point #202 is sufficiently resolved.

**Comment by tomas-knap** [comment]
Follow-up of #200

**Comment by tomas-knap** [comment]
I moved to 4th iteration as this is rather bug
