### ISSUE TITLE
Propose dialog shown behind properties when initialized from them

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#207]
Solved, but not yet merged. @KataBoku will push when the search work is done.

**Comment by tomas-knap** [comment]
@brodecva What is the status? Soved?

**Comment by brodecva** [comment]
@tomas-knap Oh, yes, solved as of https://github.com/odalic/odalic-ui/commit/6a0f44399133fee6ec7f21045c459241d22ab62f . I only forgot to close it, as all the proposal branches are not yet finished.
