### ISSUE TITLE
Include common German and Czech code pages for the character set option

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#212]
_From @brodecva on January 3, 2017 19:37_

Add following at least:
- for German: iso-8859-1, windows-1552
 -for Czech: iso-8859-2

_Copied from original issue: odalic/sti#274_

**Comment by brodecva** [comment]
Additionally, let @josef-janousek decide when some encoding is common enough in the test files to warant an addition to the defaults.

**Comment by tomas-knap** [comment]
Just a correction - "windows-1252"
