### ISSUE TITLE
When you pick a local file to upload, but stop before hitting the Upload button, and switch to remote and than back to upload, and then finally hit the Upload button, nothing happens, only the dial keeps going

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#219]

**Comment by istvan-satmari** [comment]
Reson is simple - when you switch back, the file is again, not selected. The problem I have to solve, though, is why the button "Upload" does not get disabled.

**Comment by istvan-satmari** [comment]
Finished by displaying an error message - 'the file is not selected'.
I know you may think of a nicer solution to the problem (disable button if no file is selected), but "resolving this would take too much time for a little gain".
