### ISSUE TITLE
Header must be always present

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#221]
Hi,
the server so far relies on the header being present, so when this option is turned off, it breaks when attempting to process the header.
Instead of handling this special case, I would suggest to always require the header, as even the algorithm seems to rely on the header being present quite a lot.
So unless @tomas-knap would like to support files without header or they are part of the test suite (are they @josef-janousek ?), please remove this option, @istvan-satmari, from the file configuration.
I have set the server to ignore this option, and made it optional for the client to send. When you remove it, assign this task to me, and I will remove it completely from the file configuration.

**Comment by josef-janousek** [comment]
@brodecva I think that in all files of the test suite the headers are present (even in two files there is one more extra header line which must be manually removed before processing).

**Comment by tomas-knap** [comment]
We do not need to deal with files without header.

**Comment by istvan-satmari** [comment]
Done; reassigned to @brodecva

**Comment by brodecva** [comment]
@istvan-satmari I am looking at latest commited version of develop https://github.com/odalic/odalic-ui/commit/0455725dbce77dbea99ee28e53a54fd6cdc264be , and the header present option is still there. Am I missing something?

**Comment by brodecva** [comment]
@istvan-satmari Nevermind. it is gone now. Thanks!
