### ISSUE TITLE
Unify relative positions of Accept/Save/ vs. Dismiss/Back buttons

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#222]
In some dialog the positive/acting/saving button is on the right, and the back/cancel/dismiss-like on the left, but in some (e.g. file configuration) it is the opposite.

**Comment by istvan-satmari** [comment]
I don't remember any case when cancel/dismiss/back button is on the left in any modal window...?

**Comment by tomas-knap** [comment]
@brodecva Is it still relevant?

**Comment by tomas-knap** [comment]
Reopen if needed - for no invalid
