### ISSUE TITLE
Clear the search dialog after adding the selected found entity to the candidates

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#224]

**Comment by brodecva** [comment]
> Why? A user may want to add next entities to candidates.

Fair enough. I just thought, that when you search for an entity using a substring (or prefix), you will hardly ever add multiple entries from the same result as candidates. And the more common thing would be to type another string to search for another candidate. But in the current implementation that means to first delete all the characters from the input field, which is a bit of a hassle. But I admit I may be wrong.

The second reason for that is, that without cleaning the search dialog, it just seems like we forgot to clean it. But that just also may be only me.

Let's ask others ( @tomas-knap , @istvan-satmari , @josef-janousek , @JanVana ), if they want to weigh in. Until then let's leave it open.

**Comment by tomas-knap** [comment]
When I search something and then add it, there is no sense of leaving that in a search box further. Also it is really strange if I open the dialog and there is some search string pre-set from the past.

So please adjust it in a way that after adding a string, search is cleared.

**Comment by brodecva** [comment]
> When I search something and then add it, there is no sense of leaving that in a search box AND add text box further.

Well. there you have it, @KataBoku . Thanks, @tomas-knap !

**Comment by tomas-knap** [comment]
But it is not that pressing, moved to iteration 5. Otherwise @KataBoku thanks for the search adjustments, it starts to be useful!
