### ISSUE TITLE
Propose for relations

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#228]
If I open already existing relations and I decide to propose an alternative relation, I may click propose and similar dialog as in case of proposing new class is depicted (as in case of proposing new class e.g.). There is a possibility to define name of the property, whether it is dataproperty/object property and domain/range (all just text boxes, should be already supported by backend, https://github.com/odalic/sti/issues/263)

Also please remove the "Own creation text box" as this is replaced with propose. 

Relates with: https://github.com/odalic/sti/issues/263

**Comment by brodecva** [comment]
@tomas-knap Yes, the proposal is not entirely winished client-side. I am aware of it and pressing the matter with @KataBoku .

**Comment by tomas-knap** [comment]
@KataBoku , here is the promised mockup: https://grips.semantic-web.at/display/ADEQ/Story%3A+User+can+propose+new+properties+expressing+relations

(Adjust if needed after discussion with @JanVana )

**Comment by brodecva** [comment]
@KataBoku As I recall we have agreed to not limit relation proposal only to columns with assigned classes. But this is not the case in your solution. But it is not a big deal, so I'll make another issue for that.

**Comment by brodecva** [comment]
@KataBoku Also the label is not displayed in the candidates list. Also making another issue for that.

**Comment by brodecva** [comment]
> @KataBoku Also the label is not displayed in the candidates list. Also making another issue for that.

This should work, so the issue #255 is attached to the 4th iteration. Please fix it as soon as possible. Thanks!

**Comment by brodecva** [comment]
> @KataBoku As I recall we have agreed to not limit relation proposal only to columns with assigned classes. But this is not the case in your solution. But it is not a big deal, so I'll make another issue for that.

Made into #254 , this one is OK to leave for the fifth iteration.

**Comment by brodecva** [comment]
>>  @KataBoku Also the label is not displayed in the candidates list. Also making another issue for that.

> This should work, so the issue #255 is attached to the 4th iteration. Please fix it as soon as possible. Thanks!

Oh, I forgot that even the server fails to find the label in the initial run. So this can also be postponed to the 5th one, I guess.
