### ISSUE TITLE
Get the list of available KBs and those which support insert from the API

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#230]
Already supported by the server. You can choose the primary from those that support the insertion. See REST API specs for call details.

**Comment by brodecva** [comment]
These bases list should be used not only in the task configuration, but also in the subject column selection, where only existing bases should be displayed.

**Comment by tomas-knap** [comment]
UI: Moznost definovat si KB s custom jmenem, objevi se v task manageru, muzu vybrat libovolnou, stejne tak primary KB, subject column detection to vezme v potaz, dialogy reflektuji (class, disamb)

**Comment by istvan-satmari** [comment]
Implemented list of KBs retrieval from server, though not thoroughly tested so a fallback is in place.

**Comment by brodecva** [comment]
@istvan-satmari Thanks for stepping in.

My issues with your implementation as of https://github.com/odalic/odalic-ui/commit/6a281c5196fd6f97a439cabed9d3612934154261 :
- The primary base combobox is left blank when the configuration is opened. It should have all modifiable KBs listed instead and a default value set when none has been chosen yet, for example the first modifiable base returned by the API.
- The list of available KBs should be read only and not affect the primary base combobox in any way. The selection of primary base should be done only in the primary base combo box.
- The UI might report an error when there are no KBs, or no modifiable KBs to choose the primary base from.

**Comment by brodecva** [comment]
Also:
- The validation should prevent the configuration save when the primary base is not visibly chosen.

**Comment by istvan-satmari** [comment]
Done; not tested against server, though (the rest request should be OK, but no guarantees).
