### ISSUE TITLE
Buttons on the right side of the main screens are aligned to the right and do not wrap when the screen set to smaller size

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#232]
<img width="1435" alt="screen shot 2017-01-06 at 20 57 23" src="https://cloud.githubusercontent.com/assets/3014917/21731054/c5d298c4-d452-11e6-9e38-574ed58a2e1f.png">

**Comment by istvan-satmari** [comment]
Screen-size dependent, not easy to make it look well on each device.
Should work for common screen sizes, though (e.g. 1366x768, 1920x1080).

**Comment by istvan-satmari** [comment]
Should be relatively fine now, though screen resolution should be at least around 1280x768. 1024x768 will have issues.
Also, I updated login/signup/changepassword screens, so the controls are of a reasonable length for smaller resolutions. But for 1920x1080 they are quite wide.

Anyway, the point is, it is quite hard to make it look well for each screen resolution (also tedious).
