### ISSUE TITLE
Remove Save feedback

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#244]

**Comment by tomas-knap** [comment]
We should do something with that for the demo (iter 4). I would suggest to just hide it.

**Comment by tomas-knap** [comment]
I would also suggest to disable that, because when I am clicking on that, it does nothing (from UI perspective at least), so the users would be confused that they are clicking and it does not work

**Comment by brodecva** [comment]
Closed by #262 . The button was removed.
