### ISSUE TITLE
Client should warn the user when overwriting a file definition

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#249]
When I upload a file that has the same name as some already registered, it gets to be overwritten without a notice.

**Comment by istvan-satmari** [comment]
Yes, that is expected.
Though nice-to-have functionality, not critical. Set to low prio.

**Comment by istvan-satmari** [comment]
File + Tasks

**Comment by istvan-satmari** [comment]
Needed two hacks for that:
- pull-right / pull-left for buttons in confirm modal (for some strange reson buttons got deorganized when inside "fileinput" directive)
- ignored exception thrown by angular inside "fileinput" directive - no way to detect active digest cycle there! wtf?
