### ISSUE TITLE
Error messages returned by the server trimmed by the client

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#250]
E.g. when I delete utilized file, the error message contains the names of tasks that I should change first to remove the dependency. But these are not clearly visible, because the error message is trimmed.
https://drive.google.com/file/d/0B7AckGrBKzUtVkwzRVpEbFZQM1U/view?usp=sharing

**Comment by tomas-knap** [comment]
This is quite annoying to the user, so if cannot be easily solved - maybe at least extending a bit the space for errors, that would be good

**Comment by istvan-satmari** [comment]
I solved that by extending amount of characters to 150.
Anyway, there is no nice way to do this:
- if a message is too long, it probably should be trimmed
- however since we want the messages to disappear after a while, there is no reason for adding clickable texts like "Show more" / "Show less"
