### ISSUE TITLE
It should not be possible to edit the smart combo box with suggestions

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#256]
![screen shot 2017-01-11 at 14 52 05](https://cloud.githubusercontent.com/assets/3014917/21881458/b0d339be-d8a4-11e6-81b7-55b84d3f6e8b.png)

Solution: Ensure that no one can write anything into that (when the combo box is empty)

**Comment by brodecva** [comment]
Relates to #129 .
