### ISSUE TITLE
Subject column detection does not respect selected repositories

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#257]
The list of repositories during task creation respects the KB settings. But the subject column detection does not, so when there is just dbpedia as the only KB, it still shows: 

![screen shot 2017-01-12 at 12 37 31](https://cloud.githubusercontent.com/assets/3014917/21888339/201c788e-d8c4-11e6-8fff-f02fe1c7c9e2.png)

Subject column detection, as we discussed, must respect the list of KB currently used

**Comment by brodecva** [comment]
Oh, ***. Forgot to check that in the @istvan-satmari solution. Please @istvan-satmari  or @KataBoku , could you fix that ASAP?

**Comment by brodecva** [comment]
Closed by #261 .
