### ISSUE TITLE
When proposing relations, it is not possible to define domain/range manually

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#258]
When proposing relations, it tries to fill in domain/range. But if the domain/range cannot be filled, e.g. because the classification is not available because the target column is numerical, it must be possible to fill the domain/range manually. 

![screen shot 2017-01-12 at 12 45 52](https://cloud.githubusercontent.com/assets/3014917/21888634/661246f6-d8c5-11e6-9d33-f48ae2f45578.png)

Solution: It is good to suggest, but if there is no suggestion, then there must be a possibility for the user to define it manually (e.g. by specifying a datatype, such as xsd:dateTime as a range) for columns containing dates.

**Comment by tomas-knap** [comment]
Relates with https://github.com/odalic/odalic-ui/issues/254

**Comment by brodecva** [comment]
@tomas-knap Hi, to be honest, not sure I get the datatype thing. Actually now if I remeber correctly, you proposed to give the user choice between the so called Object Types and Data Type for the relations. We were in hurry to finish the previous iterations, so this was dropped. Could you elaborate on that?

**Comment by brodecva** [comment]
@KataBoku To sum up. Derive the initial value of the domain and range from the classifications of both columns (you already do), but allow manual editing of the URI for both the domain and range, and even possible replacing of the range with a general string (to allow xsd:date and other ranges, that describe relations between a subject column and a literal value, which column was not classified). Is it clear?

**Comment by brodecva** [comment]
Finished by #291 .
