### ISSUE TITLE
Colors in result of classification gone if kb has a different name

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#259]
If I change the KB name (in the kb config, "kb.name"), the colors in the result are gone: 

![screen shot 2017-01-12 at 13 16 12](https://cloud.githubusercontent.com/assets/3014917/21889479/5f8b1dae-d8c9-11e6-9d1a-62b2dd4f047e.png)

This must be corrected. It is enough to expect there are at most 3 different KB as it was now

**Comment by brodecva** [comment]
Closed by #261 .
