### ISSUE TITLE
Integrate chosen KB concept browsing and selection component

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#26]
_From @brodecva on June 3, 2016 13:28_

Try to find existing implementation first.
Should display the context in the KB (using its ontology).
Also should be usable to pick a concept.

The implementation can be mocked in the 1st iteration.

Requirements 19. 52.

_Copied from original issue: odalic/sti#25_

**Comment by brodecva** [comment]
_From @istvan-satmari on June 15, 2016 20:12_

- Not understood. Specify in detail, what should be done. 
- To what extent does the feedback matter for the first iteration? Is it just a mean to provide a result for a user, or do we really expect a mechanism for reexecuting a task with a  provided user input constraints (= feedback)? <- THIS IS IMPORTANT QUESTION.

**Comment by brodecva** [comment]
As illustrated in the mockup at https://grips.semantic-web.at/display/ADEQ/Scenario+4b+Customizing+classification+class+-+selecting+different+non-suggested+primary+class+for+the+column+classification , this component visualizes the selected concept in the knowledge base and allows to change the used concept in the context it is opened from (when classifying column, selecting the relation predicate,...) or pick one when no concept was selected before.

It is initialized with the concept it is called upon (the used concept should imply its parental KB) and show it in its closest neighbourhood (according to the associated ontology). When opened when no concept has been selected yet, it might be necessary to choose one of the available KBs (this might be skipped for the 1st iteration, as we might be working with only one at the moment) and then it will probably display the root element (usually something general, like a "thing") according to the associated ontology.

The feedback just won't be implemented in the 1st iteration and I do not expect that we will be able to correctly implement multiple passes of the same task too in time.

For this issue and iteration it means that it is fine if this component displays only some dummy data and any actions made don't have any effect (not just for any feedback, but that the selected displayed concept won't change, although it would be really nice).

On the other hand, I guess there might be some already existing reusable visual JS/Angular components doing this, that it might in the end prove to be simpler and faster (and much more impressive) to  actually use one and attach it to our used KB (DBpedia for now) , than try to provide some mocked, not mentioning home-cooked implementation. Even in this case the chosen action might not have any effect (the concept won't be changed or filled), but at least the browsing will be working.

**Comment by brodecva** [comment]
Also notice that #63 covers providing the interface to the KB on the server, so communicate with the assignee of this issue when the time comes.

**Comment by brodecva** [comment]
Details at https://grips.semantic-web.at/x/cgBsB and https://grips.semantic-web.at/x/-wBsB .

**Comment by brodecva** [comment]
Let us use this issue to general discussion about LodLive integration that @KataBoku has done.

**Comment by tomas-knap** [comment]
Copy of my responds to @KataBoku mail about lodlive integration status: 
1) Ad vicero iframes - to bych klidne i zakazal, proste uzivatel klikne na browse (vedle stavajiciho URI), zobrazi se lodlive, pak jej pouziva, pridava URI do listboxu pres to tlacitko, pak lodlive zavre, iframe se zavre. Pokud si klikne znovu na browse u jineho URI, tak se vysledek zobrazi na miste toho prvniho. 
2) Add automaticky vyber URI, standardne bych vzdy vybiral jen jednu URI - i u klasifikace. Tzn. kdyz uzivatel prochazi lodlive, klikne u dvou trid na retizek, tak se obe pridaji do seznamu, ale vybere se automaticky jen ta posledne pridana.  Pokud chce uzivatel vic trid, ma moznost to po zavreni lodlive okna upravit v Odalic UI dialogu a vybrat jich vic. 
3) Popis prosim kratce ty (nebo nekdo jiny - domluv s Vaskem), kterak se ma Odalic instalovat s LodLive (pises nejaka omezeni - "lodLive a odalic-ui musí být ve stejné složce")
4) Vypada to, ze kdyz nekdo vybere nejaky koncept pres lodlive, tak dostane jen URI, ne label. Je to tak? Toto zatim nech, vyzkousim a rozhodneme co s tim.
