### ISSUE TITLE
Support primary KB display and setting in all appropriate contexts

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#27]
See https://grips.semantic-web.at/x/cYVlB for details.

**Comment by brodecva** [comment]
The change prepared in https://github.com/odalic/sti/pull/96 requires the client to add a primary KB specification used during a task processing. The changed task object sent to the server should look like this from now (the addition is bold):
`(TS1)

{ "id": "simple_task", created: "yyyy-MM-dd HH:mm", "configuration": { ... } }

For configuration object description, see below.

(TS2)

{ "input": "file description ID", feedback: { ... }**, "primary_base": { "name": "DBpedia" }** }`

**Comment by tomas-knap** [comment]
This does not work correctly, see: https://github.com/odalic/odalic-ui/issues/36

**Comment by tomas-knap** [comment]
Blocked by #36

**Comment by brodecva** [comment]
> This does not work correctly, see: #36

It workis. Will be resolved by merge of the working branch.
