### ISSUE TITLE
Present the non-aborting processing errors

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#270]

**Comment by brodecva** [comment]
Waits for https://github.com/odalic/sti/issues/166 .

**Comment by tomas-knap** [comment]
Prio set to High, as it waits for odalic/sti#166

**Comment by tomas-knap** [comment]
Please try to address that 7.2., odalic/sti#166 should be prepared by 6.2. by @JanVana

**Comment by istvan-satmari** [comment]
Address any comments to #308
