### ISSUE TITLE
implement user management on the client side

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#272]
- First do only some research on the topic. Expected solution should be based on token-based authentication. Check satellizer. https://grips.semantic-web.at/login.action?os_destination=%2Fpages%2Fviewpage.action%3FpageId%3D76226993&permissionViolation=true

Done:
  - rest requests extended with token (automatically injected to $http via satellizer)
  - if not logged and a privileged action occurs (e.g. retrieve files) - automatic redirection (via custom interceptor)
  -  sign up screen (functionality)
  - login screen (functionality)
  - logout button
  - password change + confirmation token
  - displaying login/signup buttons if not logged in, displaying logout button if logged in (extend json with "condition: "$scope.logged"" or something like that for each button, and test it)

Remains:
- testing

**Comment by istvan-satmari** [comment]
Research done, described in the corresponding page on grips.
Now waiting for the server to implement JWT.

**Comment by brodecva** [comment]
@istvan-satmari Alright, I will look into it ASAP.

**Comment by tomas-knap** [comment]
Ok, lets leave the possibility to log in via google account as another quite cool feature if time permits
