### ISSUE TITLE
I should be able to select only subset of available KBs

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#274]
Currently, all KBs are used for each task. There should be possibility to select only a subset of KBs

**Comment by tomas-knap** [comment]
Motivation: During demo, I have couple of tasks, using different KBs. If I always use all KB it is a bit confusing. If that means some more changes than just enabling user to multiselect KBs and store that into the conf, please let me know.

**Comment by istvan-satmari** [comment]
It was implemented that way before until somebody told me that only primary KB is to be selected. (In the meaning  that primary base could be selected only from the selected subset of KBs)
...so, a revert will be necessary

**Comment by tomas-knap** [comment]
Ok, thanks!

**Comment by istvan-satmari** [comment]
to @brodecva  : I believe the API on the server is missing:
"primaryBase": { "name": "DBpedia" }
this is only "set-able" option.

**Comment by brodecva** [comment]
@istvan-satmari I have added "usedBases" field, which is a name-ordered set (encoded as JSON array) of KB objects. When set by the client, the order does not matter. When null, all available bases are used (this is for backward compatibility).

**Comment by brodecva** [comment]
@istvan-satmari Please do not forget to use the value from "usedBases" not only during the task configuration display, but also whenever the client formerly asked for all available bases apart from the task configuration (it was in relations setting, I think, ask @KataBoku for details).

**Comment by istvan-satmari** [comment]
Presumably done.
