### ISSUE TITLE
The selection of Primary KB does not work

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#275]
It seems that only the first KB (editable) can be selected. SO I have couple of KBs, I try to select the second one as KB: 

![screen shot 2017-01-19 at 12 21 04](https://cloud.githubusercontent.com/assets/3014917/22104967/05c357b8-de42-11e6-8baa-33b42453a2b6.png)

Then I save it, reopen the task and there is again ADEQUATe (the first one)

![screen shot 2017-01-19 at 12 21 11](https://cloud.githubusercontent.com/assets/3014917/22104962/ffb2d3b2-de41-11e6-8d7f-1f62b2f673f0.png)

**Comment by tomas-knap** [comment]
@istvan-satmari @KataBoku If you can address that today, would be great, as otherwise I am not able to have demo with two tasks using two different primary KBs, which was the idea. Thanks!

**Comment by istvan-satmari** [comment]
Rather difficult to resolve if I have no such options among KBases. How do you test that?

**Comment by tomas-knap** [comment]
I have realized that if you create a fresh task with the desired conf, it works. But if you later click "view/edit the task configuration", it shows wrong primary KB (the first one?, although the algorithm correctly used the previously selected) and it does not allow to change that - do the problem is when view/editing the task conf from the list of tasks

**Comment by tomas-knap** [comment]
@istvan-satmari You should be able to test that at: http://adequate-project-odalic-ui.semantic-web.at/odalic-ui/#/

**Comment by istvan-satmari** [comment]
Basically solved; waiting only until server implements "KBs subset selection".
