### ISSUE TITLE
When you create task that has the same ID as an existing one, it breaks things

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#279]
You should either check, or take into considerations that for example the computed result is lost and therefore you should not display the button to see it anymore. If you do, a preventable error appears, informing that the computed result is gone.

**Comment by istvan-satmari** [comment]
Even though it may seem logical for UI to:
1. send a request to get list of created tasks
2. check if any of the tasks' name is identical to the one currently being created...
...this should be checked by the server anyway. Note that server basically provides a public API so it has to deal with such issues. I believe the correct behaviour in this case is server returning a certain error response (status code 4xx? conflict?).

UI should be able to deal with such a response from the server already (by displaying alert/toast/...), so no further work is necessary, I think.

**Comment by brodecva** [comment]
> Even though it may seem logical for UI to:
>
>    send a request to get list of created tasks
>    check if any of the tasks' name is identical to the one currently being created...
>    ...this should be checked by the server anyway. Note that server basically provides a public API so it > has to deal with such issues. I believe the correct behaviour in this case is server returning a certain error > response (status code 4xx? conflict?).

Well the thing is that the server has no way to recognize whether you are merely attempting to replace the task, or if you made a mistake, and are replacing it with another. Well not unless a PATCH HTTP method is used, but this is a bit complicated to implement both at the client and server the right way.

> UI should be able to deal with such a response from the server already (by displaying alert/toast/...), so no further work is necessary, I think.

Well... It seems that the problem was that I failed to update the execution state. I will fix that. For now this might get lower priority and be moved to 6th iteration.

**Comment by tomas-knap** [comment]
It should be ideally solved at the server, as Istvan said, returning e.g. 409?, conflict. But if it is easier to do that in a way that UI first asks (via a separate service) if there is name clash and if yes, displays error, I would go this way.

**Comment by brodecva** [comment]
This issue was moved to odalic/sti#342
