### ISSUE TITLE
UI fails to notice successful finish of a second task

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#281]
Reproduce by creating (not running yet!) two tasks, e.g. using the Books file. Then start the first task, wait few seconds and start the second one.
When the first task finishes, the UI correctly reports that. But when the second one does finish, the UI fails to notice it and still displays the "in progress" icon.
I have checked the requests made by the UI, and it seems it is sending requests for the state of the first task, instead of the second one.

**Comment by istvan-satmari** [comment]
Done; paging branch.
