### ISSUE TITLE
When opening detail for relations, the combo box with suggestions not available

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#285]
<img width="594" alt="screen shot 2017-01-24 at 10 18 02" src="https://cloud.githubusercontent.com/assets/3014917/22241193/a840f998-e21e-11e6-89fe-e0f53292c847.png">

For some reason, it does not show the combo box with the suggested relations

**Comment by tomas-knap** [comment]
There is no way to delete relation thanks to that! Increasing prio

**Comment by tomas-knap** [comment]
Again, if you can fix asap would help me - do not need to look for last version which worked and cherry pick the rest ;)

**Comment by brodecva** [comment]
@tomas-knap Hi, I cannot reproduce it. Which file did you use?

**Comment by brodecva** [comment]
@tomas-knap @KataBoku But what I noticed is this: https://github.com/odalic/odalic-ui/issues/287 .

**Comment by tomas-knap** [comment]
This one is solved, see: https://github.com/odalic/odalic-ui/commit/95e0da7366fbef31a27af8a19e6156cf5727fe66
