### ISSUE TITLE
Cannot propose custom relation

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#287]
When I click OK nothing happens, not even a reqeust is fired.

**Comment by tomas-knap** [comment]
Still working at: 4915f3db9be580ac6a13b2a2a2f1e3b345e840e7

**Comment by tomas-knap** [comment]
I closed that by accident - NOT SOLVED (I solved #285 with the above mentioned commit) Sorry for a bit of confusion

**Comment by tomas-knap** [comment]
Btw. cannot reproduce that, seems to be working for me (tested agains Jan's dbpedia)

**Comment by tomas-knap** [comment]
@KataBoku Please discuss with @JanVana the steps to reproduce

**Comment by brodecva** [comment]
@KataBoku @tomas-knap Works for me too. Ah, maybe I should have hit the Ctrl-F5 harder.

**Comment by brodecva** [comment]
Re-opening. It still happens. Steps to reproduce:
1. Run this file http://www.ms.mff.cuni.cz/~brodecva/odalic/Books-v2-utf8.csv .
2. When finished, open the results and go straight to the relations display.
3. Switch to Link creation and draw a line between Series and Author.
4. Click Propose and enter a unique label.
5. Hit OK -- nothing happens! The server receives the request and successfully sends back the proposed resource. But the client does nothing! Only the console prints the following: "Error: currentRelation is not defined"
