### ISSUE TITLE
Create prototype of relation display

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#30]
Explore d3 details.

**Comment by tomas-knap** [comment]
Also there is wiki page, please write your findings there: https://grips.semantic-web.at/pages/viewpage.action?pageId=74187780

**Comment by istvan-satmari** [comment]
Done. Also see https://github.com/odalic/odalic-ui/tree/relations for further details.

**Comment by brodecva** [comment]
Back to in-progress as Istvan has to make the demo fulfil the proposed requirements.

**Comment by istvan-satmari** [comment]
Basically done. D3js provides a lot of features to allow for a development of the component; for manipulating graphs we have the dagre-d3 library, which greatly simplifies the development.
