### ISSUE TITLE
When not logged in, both files and  tasks overview appear for a short time before being replaced by login screen

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#302]
The login screen should appear immediately. Is it possible?

**Comment by istvan-satmari** [comment]
Not really - in any case I have to send an asynchronous request to the server that detects whether a user is logged or not. So basically reload happens immediately after a first request which server responds to with "unauthorized" status. (Visuals of the page get obviously loaded before the server responds.)

There is one option - wrap all of the pages around "loadico" directive (basically displaying "loading..." icon until server responds), but this seems like a lot of work for too little gain.

Closed as won't fix.
