### ISSUE TITLE
Create button permanently replaced by spinning clock when primary base not chosen and Create clicked

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#304]
To reproduce go to Create a task. Fill the name, choose existing file, choose KBs, but select no primary. When you click Create, the spinning clock appears and error message is shown under the primary base input. But even when you select the primary base, the spinning clock remains and there is no way to only Create (and not immediately run the task).

**Comment by istvan-satmari** [comment]
Yeah, I forgot to call a "future" (async callback method) upon unsuccessful validation. My bad.
