### ISSUE TITLE
Tooltips when mouse over for a second e.g. for lock icon etc.

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#306]
For the icons:

![screen shot 2017-02-03 at 11 14 03](https://cloud.githubusercontent.com/assets/3014917/22587429/efe306e8-ea01-11e6-9022-1e205e004f4b.png)

In the dialog - class detail: 
![screen shot 2017-02-03 at 11 13 52](https://cloud.githubusercontent.com/assets/3014917/22587434/f3303212-ea01-11e6-8a51-d9f4e187a262.png)

**Comment by istvan-satmari** [comment]
Done. Though I am not sure about the text displayed (maybe next time it would be useful to describe that as well? Thanks!)

Btw, tooltip over "trash can" is not possible - @KataBoku  used bootstrap "pull-right" class for the corresponding icon which messes up with tooltip's basic functionality.
