### ISSUE TITLE
Hide controls form non named entity columns?

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#312]
From Ziqi: In case of column not containing named entities, it does not make sense to provide those control buttons for editing detail of the classification, proposing new, locking the column etc. SO the idea is just to hide such controls for columns evaulated by the algorithm as non-named-entities, thus not being classified. 

To consider - as it may happen that certain column contains numbers, it is not classified, but I may try to explicitely introduce classification, disambiguation. TODO: Question is whether in this case it will work anyway as such column will be anyway ignored during re-execution of the algorithm

**Comment by brodecva** [comment]
@tomas-knap @josef-janousek Well, as you or Ziqi said, if the user can manually disambiguate some cells in the column, so the controls are needed than.
I propose to leave it as is.

**Comment by tomas-knap** [comment]
Yes, lets close as won't fix for now
