### ISSUE TITLE
Add option to define files independently to task creation

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#317]
I realized we actually need this in order to satisfy the case when someone exports the task config and the referenced file gets deleted or the confi is imported to another server.
Yes, you can define the file in the task config creation screen without actually creating a task, but this is really clunky.

**Comment by istvan-satmari** [comment]
This takes rather a longer time to implement.
I'll think about it, but there has been already a lot of tasks lately and I have other work to do. Besides, I still blame graph component for taking a lot of time to implement that could have been used for features like these.
This is definitely postponed.

**Comment by istvan-satmari** [comment]
Done, but I just reused the component from task creation screen.
It would be tedious (not hard, just annoying and lengthy) work to make a completely new screen.
