### ISSUE TITLE
Make the alternative/extra disambiguation/classification selection comply with the story "User can select alternative/extra classification/disambiguation"

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#32]
More at https://grips.semantic-web.at/x/cgBsB .

**Comment by KataBoku** [comment]
I think, here is some misunderstanding. UI can display multiple KBs. I supposed the result of algorithm is in this format : https://grips.semantic-web.at/display/ADEQ/REST+API%3A+1st+iteration+THE+REAL+ONE. So I expected, same URL  prefix from one knowledge base, but there are more URL prefixes in our test example. So what should I do? Is it the problem in server or client part? (Example of result from dbpedia: "http://dbpedia.org/ontology/Book","http://www.wikidata.org/entity/Q571","http://schema.org/Book")

**Comment by brodecva** [comment]
Still missing label display. Will be done tomorrow.

**Comment by brodecva** [comment]
Done.
