### ISSUE TITLE
Browsed item remains selected + border of the icon

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#323]
Steps: 

1) I run task for Books-v1.csv
2) When I click on the detail for the class s:Book, I got:

![screen shot 2017-02-08 at 10 44 13](https://cloud.githubusercontent.com/assets/3014917/22731759/0777706c-edec-11e6-8f29-a0708c96a18b.png)

Why is the icon with the blue border? 

3) If I click on that link from the detail and return back, the item is highlighted and there is no easy way how to get rid of that: 

![screen shot 2017-02-08 at 10 44 25](https://cloud.githubusercontent.com/assets/3014917/22731757/07726e1e-edec-11e6-9974-e677993973af.png)

Solution: 
- icon "i" should not have blue border
- when returning from the detail, the item in the combo box should not be highlighted

**Comment by tomas-knap** [comment]
The same applies also in case of details for relations

**Comment by tomas-knap** [comment]
Please discuss with @istvan-satmari if needed to fine tune

**Comment by KataBoku** [comment]
It is not my styling. The fields are marked for the alternative control by keyboard without mouse. The icon "i" has the first tab index so it is marked. I admit it is not nice so i canceled the blue border. I would like to let the other fields marked.
