### ISSUE TITLE
In case of statistical data, subject column detection phase must be skipped.

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#324]

**Comment by brodecva** [comment]
Just checking with @josef-janousek , that this is really the case? Did you miss it, or is there a reason why you did not object that the subject column selection is still present?

**Comment by josef-janousek** [comment]
@brodecva Yes, it is correct, the Step 2 (subject column) should be hidden for statistical data. I forgot it, because I focused on functions of Step 3 (data cube) (which would be then probably renamed to Step 2).

**Comment by brodecva** [comment]
>Yes, the issue is correct, so the Step 2 (subject column) should be hidden for statistical data. I forgot it, because I focused on functions of Step 3 (data cube) (which would be then probably renamed to Step 2).

Thanks, @josef-janousek !
