### ISSUE TITLE
Adjustments of icons for dimensions/measures, the buttons style, height of the combo box

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#325]
In case of statistical data dialog, currently it looks as follows: 

![screen shot 2017-02-08 at 10 58 59](https://cloud.githubusercontent.com/assets/3014917/22732273/e230327e-eded-11e6-93d7-6895783deb82.png)

What I do not like is that the icons. 

Can you please move the "details, lock, propose" icons to the second column, as it is in the cells in Step 1? And for the last icon, "delete", please leave it in the last column (which should be renamed to "Action" in a same way as in task configurations list) and also please provide such "delete" icon in the button style. 

If it is too complicated to add "details, lock, propose" icons to each cell in the second column (as in Table with class/disamb), please let me know. We may also create buttons from that icons in the last column.

**Comment by tomas-knap** [comment]
Also please adjust the button "Add to dimensions", "Add to measures", so that it looks like the other buttons (e.g. Search, Propose in dialogs), or as "Next step" below. Otherwise it is awful. 

Also please make the height of the combo box and the button the same: 
![screen shot 2017-02-08 at 11 06 55](https://cloud.githubusercontent.com/assets/3014917/22732515/bb7ca314-edee-11e6-9d43-b2fa81a6d412.png)

**Comment by brodecva** [comment]
> And for the last icon, "delete", please leave it in the last column (which should be renamed to "Action" in a same way as in task configurations list) and also please provide such "delete" icon in the button style.

@KataBoku I think that @tomas-knap meant to use the "bin" icon. The black cross does not really fit.

**Comment by brodecva** [comment]
@KataBoku Otherwise OK.
