### ISSUE TITLE
After failed task run, clicking the result to display the causing error does nothing, only spinner appears

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#326]
_From @brodecva on February 10, 2017 6:36_

This used to work.

How to cause task failure: e.g. turn off the internet. ;-)

_Copied from original issue: odalic/sti#367_

**Comment by istvan-satmari** [comment]
Not sure whether now works, since it is complicated to cause an error (not warning) in task execution.
Though I suppose I corrected it by setting an accept-type header since the UI was not displaying result for successful tasks either.
