### ISSUE TITLE
When deleting a file, the client does not set Accept header to application/json, so it does not receive error message when something goes wrong.

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#327]
_From @brodecva on February 9, 2017 22:14_

This results in message "... (Server responded with empty message...)" instead of displaying the true reason when deleting file used by existing task.

Just set the Accept to application/json, this should resolve that. Otherwise the server won't send the message, but an empty response.

Weird thing: this used to work. What changed?

_Copied from original issue: odalic/sti#366_

**Comment by istvan-satmari** [comment]
Accept header added. But...
...it is rather weird.

DELETE http://localhost:8080/odalic/files/myfile.csv does not work - results in 409 conflict. The accept header is correctly set, though. (The file exists as well.)
Additionally, I would expect server would respond to this:
DELETE http://localhost:8080/odalic/files/non_existent_file with an appropriate message; instead it only returns status 404 but no message attached.

Any ideas what went wrong?

**Comment by brodecva** [comment]
@istvan-satmari OK, in the end this was a server issue, that was masked by previous liberal content of the Accept header sent by client. Fixed as of https://github.com/odalic/sti/commit/b41ce211e2fd03bcfbde7c04a195d45995552789 .

**Comment by brodecva** [comment]
@istvan-satmari Thanks for reproting!
