### ISSUE TITLE
The warnings, although properly sent by the server and under correct state, not displayed

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#328]

**Comment by brodecva** [comment]
The warning state was detected by the client, alright. Even the message when displaying the result about some problems was displayed to. But after clicking Learn more only empty table with a header was displayed. But there was a plenty of warnings sent.

**Comment by istvan-satmari** [comment]
The problem is the warnings contain the same message - this causes indexing problem for angular and throws an exception (so the modal is empty). Solved by using "track by $index".

Additionally the modals did not have "x" (close) button, so corrected that as well. I somehow forgot about that.
