### ISSUE TITLE
Relations graph component

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#33]
Create the graph visualizing component satisfying the corresponding requirements on grips portal. The graph component will be created using solely D3js.
TODO (will be adjusted):
- Study D3js API
- Fork a graph example, edit it to suit our needs, or create a new
- Result should be a basic dynamic graph (i.e. draggable), understand its API, make it easy to add new vertices, edges, or to remove them. Maybe create a wrapper.
Other TODOs will be added later as soon as this is completed.

**Comment by istvan-satmari** [comment]
(Making the size of the issue greater since, of course, as expected, d3js made trivial tasks unnecessarily complicated. What's even better is they decided to change API in v4, so most of the examples don't work, as they were written using v3...)

**Comment by brodecva** [comment]
These @tomas-knap notes from the meeting:
- make the edges thinner, they are not mean to be clicked, only the label
- draw a thin line around the vertex circle
- make the vertices larger
- better separation of concepts sharing the same edge is needed, e.g. alternating colors
- put the concepts from facing directions on the opposite sides of the edges

**Comment by istvan-satmari** [comment]
Done except: "better separation of concepts sharing the same (side of) edge is needed, e.g. alternating colors". 
A couple of problems: 
- mouseover / mouseout: already changes colors of the labels
- svg element <text> does not implicitly support it (only using <span> or similar means, but then positioning problems ("x, y") arise)
- what colors? random? it wouldn't match the rest of the GUI then

Anyway, for the current iteration I won't be making further changes to the component.
