### ISSUE TITLE
Re-add Save feedback button

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#338]
Please re-add the "Save feedback" button, which saves what the user does as he was observing the result.  The label could be just "Save", should be on the right together with "Cancel" button, see: https://github.com/odalic/odalic-ui/issues/340

When he re-open the feedback next time, it should be available with the changes he did. 

Motivation: So that he does not need to re-executed to save the feedback.

**Comment by brodecva** [comment]
OK, but @istvan-satmari , please add some TOAST confirmation (I think that this was the reason it went out: clicking it did nothing from the perspective of the user).
