### ISSUE TITLE
Warning when there is already existing file which should not be overwritten

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#339]
Steps: 
1) Upload new file with the same identifier
2) It warns me whether I would like to rewrite. 
3) Say no

As a result, there is no status message so I do not know whether it was created or not

Solution: Please add proper info message (probably red one that it was not created because such file already exists)

**Comment by brodecva** [comment]
@tomas-knap Personally this does not seem like an issue to me. It is clear that when you reject the upload that nothing happens and the file is not uploaded. How could be? It shared a name with an existing one and that is what caused the prompt to appear. Assigning a low priority, unless you insist.

**Comment by istvan-satmari** [comment]
Sorry, I am closing the issue. From the UX perspective it seems fine to me - let me demostrate:
- upload file with the same ID
- modal is opened
now 2 options: reject (nothing happens), or accept - the user is informed with the green alert that the file has been successfully uploaded / attached.

It seems weird to me to warn a user, that he "successfully rejected file overwrite", don't you think?
(as for task creation, there it is also clear - when rejected, user stays on the task creation page; when accepted, user is redirected)

**Comment by tomas-knap** [comment]
OK, acceptable. Maybe what is missing is some info that you should change your identifier to actually upload it succesfully
