### ISSUE TITLE
Import with no config file behaves strange

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#344]
If I click import without defining (uploading) the config, there is just a circle and nothing happens

![screen shot 2017-02-15 at 11 26 01](https://cloud.githubusercontent.com/assets/3014917/22970211/9d1b84c0-f371-11e6-8e0e-6231f4c7ffd6.png)

Please write an error message (red) in this case.

**Comment by brodecva** [comment]
I have fixed it by detecting the missing content at the server and throwing BadRequestException which client automatically displays in https://github.com/odalic/sti/commit/39741a2c520f10f1e2a75b2a4c8a480ca149b4d7 . This sorts this out. Closing.
