### ISSUE TITLE
When running the task just created, display the page it is on

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#345]
Otherwise when re-directed I cannot immediatlaly see the newly created running task.

**Comment by istvan-satmari** [comment]
pagination

**Comment by istvan-satmari** [comment]
maybe use ordering
- call order by id
- change "date created" to "date changed"

**Comment by istvan-satmari** [comment]
Resolved by adding "orderedBy=created" in the corresponding rest request. "Date created" has been changed to "Last modification" to better represent the actual data.
