### ISSUE TITLE
Buttons - text does not fit

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#351]
New task, resize
<img width="418" alt="screen shot 2017-02-17 at 13 12 54" src="https://cloud.githubusercontent.com/assets/3014917/23064908/07ef4abe-f513-11e6-8e77-a9781c25b0cd.png">

**Comment by tomas-knap** [comment]
If you can do anything with that

**Comment by istvan-satmari** [comment]
Should be OK now
