### ISSUE TITLE
SSL support for commutation between frontend and backend

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#352]
hm, dotaz, ktorý mi napadol až teraz: budeme robiť niečo s SSL encryption? Momentálne by nám mohli vytknúť, že odosielanie tokenov na server nie je nijak chránené proti odposluchu

dobra pripominka - pokud by tam byl SSL mode, tak je to urcite plus - na strane serveru by to melo byt snadne, na strane klienta by to znamenalo pouzit jina URL, jinak asi ta knihovna, kterou pouzivame pro requesty si s tim poradi, ne? Urcite prosim sepis co by bylo treba udelat, aby tam ta podpora byla. Pak muzem rozhodnout, zda to jeste delat nebo ne

**Comment by tomas-knap** [comment]
Summary: Just write a section to installation guide how to deploy that with SSL

**Comment by istvan-satmari** [comment]
Possibly only ~1 paragraph about the issue; won't be explained in detail how to configure. Only that it is possible.

**Comment by brodecva** [comment]
> Possibly only ~1 paragraph about the issue; won't be explained in detail how to configure. Only that it is possible.

@istvan-satmari Thanks, could you do that, please? Maybe slightly extended note from the Skype conversation would suffice.
