### ISSUE TITLE
predicateObj.predicate.chosen is undefined exception

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#354]
...
However, what I noticed is there is a strange bug occurring sometimes - solely when working with task with statistical data set.

I get this exception thrown:
Error: predicateObj.predicate.chosen is undefined

Steps I took:

1. go to result of a task with statistical data set
2. go to next step
3. make a change (e.g. remove a dimension)
4. click save feedback
5. click reexecute (I get the aforementioned exception, which results in that I never get taken back to task configs screen and the button is replaced by a spinner indefinitely. The bug therefore seems to be in controllbuttons.js > sendFeedback function.)

Additionally, after taking these steps, when returning to task configs screen, it is necessary to take these steps only to get the same exception again:

1. go to result of a task with statistical data set
2. click save feedback
3. click reexecute

@KataBoku , any ideas about this?
...

**Comment by tomas-knap** [comment]
@KataBoku please write shortly where the problem was

**Comment by tomas-knap** [comment]
@istvan-satmari Can you please retest if solved?

**Comment by istvan-satmari** [comment]
Branch blinkingDataCube, works well. OK
