### ISSUE TITLE
Degradation of UI performance (showing results)?

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#361]
It seems to me that there was certain degradation of UI performance (~3x slower in case of the file below) caused by some commit between 19.1. and now (tested on the branch origin/blinkingDataCube). 

Steps:
1) Try to execute the file below with the current develop branch and click "show results" from task list. You have to wait couple of long seconds (3-4 in my case)
2) Try the same file with the version of Odalic at https://github.com/odalic/odalic-ui/tree/demo branch (approx from 19.1.) and and click "show results" (the results are ready in a second).  

One candidate is paging, but I think it is not caused by that. 

File: 
[STMK_2012_LIVEBIRTHS-10lines.csv.zip](https://github.com/odalic/odalic-ui/files/797074/STMK_2012_LIVEBIRTHS-10lines.csv.zip)

Can you pls check that briefly on that file - both version on localhost? Thanks!

**Comment by istvan-satmari** [comment]
The data seems to contradict the observation. I've already sent an e-mail regarding the issue. Closed

**Comment by tomas-knap** [comment]
Tu posielam podrobný report:

Vytvoril som špeciálne branches nad oboma verziami (performance-measure-latest a performance-measure-demo), do ktorých som narýchlo doimplementoval stopky (vypisujú do konzole, teda treba mať otvorené developer tools).

A stopoval som čas na týchto miestach:
- po kliknutí na "go to result" z taskconfigs obrazovky sa započnú stopky
- "Result downloaded." - stopnutie po tom, čo sa vráti výsledok zo serveru
- "All data loaded." - stopnutie po tom, čo sa vrátia všetky požadované dáta zo serveru (napr. feedback, samotný obsah súboru - csv-čka, ...)
- "Set to show the content." - stopnutie po tom, čo sa nastaví istá premenná na true, aby sa mohol zobraziť obsah výsledku (dokým sa nenastaví, tak tam bude tá spinner ikonka). Evidentne, tu to je zbytočné, pretože Angular prevedie digest cycle asynchrónne (týmto som si nebol istý). Takže tento bod možno odignorovať...
- "Clicked on the button." - doimplementoval som tlačidlo, ktoré sa zobrazí spolu so zvyšným obsahom, pre tzv. manuálne stopnutie (stlačil som ho vždy hneď po tom, čo sa zobrazila tabuľka)

Ešte "terminológia":
- Point. Time diff: 390: rozdiel oproti času od započatia stopiek
- Ring. Time diff: 3: rozdiel oproti poslednému stopnutému času
Všetky časy sú v milisekundách.

Merial som zvlášť pre "5 riadkov", "10 riadkov" a všetky riadky (tuším 15); aby sa aj ukázalo, či ten pagination mal zmysel (verzia "demo" pagination ešte neobsahovala). A aby som si to potvrdil, každé meranie som opakoval 5x.

Zhrniem len priemerné časy:
DEMO 5L: 2355 / 2992
DEMO 10L: 2486,4 / 3175,4
DEMO ALL: 2647,6 / 3344

LATEST 5L: 2131,4 / 2828,2
LATEST 10L: 2486,4 / 2446,8
LATEST ALL: 2098,2 / 2728,8

Čas pred lomítkom: čas potrebný pre vyrenderovanie tabuľky
Čas za lomítkom: čas uplynutý od kliknutia na "go to result" až po vyrenderovanie tabuľky

Je pravda, že odchýlka je relatívne veľká (~1s), ničmenej aj tak mi príde, že časy pre "latest" a "demo" verziu sú dosť podobné a rozdiel by nemal byť citeľný. Nehovoriac o tom, že pre "all lines" "latest" verzia prekonáva "demo" - potrebuje totiž vyrenderovať iba 5 riadkov, oproti 15 (v skutočnosti ~13, pretože "demo" obsahovalo chybu v controlleri, čo spôsobilo vynechávanie niektorých riadkov). V "demo" variante je celkom evidentné, že s väčším množstvom riadkov rastie aj čas potrebný na vyrenderovanie, čiže ten pagination nakoniec nie je zbytočný (aj keď rozdiel asi bude cítiť až pri výrazne väčších dátach).

Namerané časy prikladám v prílohách, pokiaľ to chce niekto skúmať. Branches zatiaľ nechám na GitHub-e tiež z rovnakých dôvodov. Ničmenej musím upozorniť, že "demo" verzia ešte neobsahovala autorizačné hlavičky v request-och (...som zvedavý, jak si to vlastne vyriešil? existuje pre toto nejaký centrálny prvok v browser-i...?), takže som ich musel "centrálne" preťažiť (src/services/requests/request.js) => pokiaľ by to náhodou niekto chcel použiť, nech si skopíruje svoj súčasný token, ktorým sa podpisuju request-y a nastaví ho do premennej "token" v danom zdrojáku.

Ešte posledný detail - pred meraniami som robil "warmup", lebo mám skúsenosť, že po dlhšej neaktivite mi server odpovedá pomalšie (pravdepodobne tým, jak mám malú RAM-ku a Windowsy swapujú, tak to je občas cítiť).
