### ISSUE TITLE
When task configuration is changed, the UI sents en empty feedback instead of the current one

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#363]
I have fixed the behaviour on the server, but https://github.com/odalic/sti/issues/356 must be also supported by the UI. The UI should send the current feedback when changing the task configuration, not an empty one. Otherwise, the task has to be naturally re-run.
Unless you somehow keep the feedback in memory, this means that you should make a request for it before updating the config.

**Comment by brodecva** [comment]
@istvan-satmari @tomas-knap This is naturally bit compliated. The UI should send an empty feedback whenever a setting that affects the feedback is changed. Therefore sent an empty feedback all the time, but in case only the description is changed, sent the current one.

**Comment by istvan-satmari** [comment]
Done, but I did not test it against the latest version of the server. But the client does send the feedback only when the description is changed, so that part should be OK.
