### ISSUE TITLE
Reduce the space occupied by the logo "Odalic"

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#366]
3cm of the screen are covered by orange banner with "Odalic". Please make it less prominent and more space to task view. 

This may be pointed out by the opponents

**Comment by brodecva** [comment]
@tomas-knap Agreed. Thx for noticing.

**Comment by istvan-satmari** [comment]
Removed space around the logo. Check and let know, if OK.

**Comment by tomas-knap** [comment]
OK
