### ISSUE TITLE
It is not clear which color represents which KBs - ideas?

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#367]
When observing results of more KBs, e.g. http://odalic.eu-gb.mybluemix.net/odalic-ui/#/taskresult/unternehmen, it is not clear which color represents which KBs (one can distinguish only based on URIs)

![screen shot 2017-02-27 at 14 23 10](https://cloud.githubusercontent.com/assets/3014917/23362938/5bc160f4-fcf8-11e6-8375-f4c973d0a4ba.png)

But do not know what to do with it in couple of hours. Maybe a tooltip shown when pointing on the table header which shows not just "named/non-named entity", but also names of KBs with the corresponding background? Suggestions welcomed ;-)

**Comment by istvan-satmari** [comment]
A tooltip added. Check, if OK, but note that no other solutions will be proposed (due to the lack of time).

**Comment by tomas-knap** [comment]
OK
