### ISSUE TITLE
Fix LodLive back-propagation of the picked resource

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#371]

**Comment by tomas-knap** [comment]
@brodecva Can you pls describe more?

**Comment by brodecva** [comment]
@KataBoku has to fix the case when a resource is picked in the LodLive. This fails to propagate back to Odalic UI. This was broken in some of the later additions (probably the prefixes), and unfortunately not detected until last week.

**Comment by brodecva** [comment]
> has to fix the case when a resource is picked in the LodLive. This fails to propagate back to Odalic UI.

Basically selecting different resource in LodLive is an alternative mean to change the chosen resource for disambiguation or classification. This was broken and has to be fixed. Should be simple to do so, according to @KataBoku .

**Comment by brodecva** [comment]
Fixed by https://github.com/odalic/odalic-ui/pull/372 .
