### ISSUE TITLE
The logo causes screen space waste

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#375]
Reduce the size and/or move elswhere.

In Czech:
Design: Logo projektu zabírá příliš velkou část obrazovky a nemá žádnou funkcionalitu -
jedná se tedy o vyhozený prostor

**Comment by tomas-knap** [comment]
Size was already reduced a bit in the last iteration

**Comment by istvan-satmari** [comment]
Done. Whatever.

**Comment by brodecva** [comment]
> Done. Whatever.

Can't see the difference...

**Comment by brodecva** [comment]
As I recall we have decided to practically remove the top bar containing the logo and moving the logo left to the items. If not possible then reduce the size of the logo and definitely not leave so much space above and bellow.

**Comment by istvan-satmari** [comment]
"Can't see the difference..."

Did you check develop branch?
=> https://github.com/odalic/odalic-ui/commit/efda0bfbf1ab9e019945e7d04e29592dbcaf1e81
