### ISSUE TITLE
SPARQL queries used contain too many, unutilized prefixes

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#376]
In Czech:

Dokumentace v dotazech obsahuje nesmyslně mnoho prefixů které nejsou použity, např. strana 86

**Comment by tomas-knap** [comment]
Goal: Remove the prefixes from the doc?

**Comment by tomas-knap** [comment]
But this is only issue in the documentation, do not adjust anyhow in the code!

**Comment by brodecva** [comment]
Once established the prefixes are omitted from further examples in https://grips.semantic-web.at/display/ADEQ/Core+algorithm+description .
