### ISSUE TITLE
Default parsing CSV format uses semi-colons instead of the standard comma

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#377]
In the catalogues, the semicolons are more frequent. So maybe not fix?

In Czech:

Výchozí oddělovač CSV není standardní čárka, ale nestandardní středník

**Comment by istvan-satmari** [comment]
I'd say if the semicolon is more frequent then the fix is pointless.

Anyway, it seems I cannot fix this in UI - upon a file creation UI does not send any data regarding the file format, only the file itself. However, the server seems to assume the default delimiter to be the semicolon.

**Comment by brodecva** [comment]
> I'd say if the semicolon is more frequent then the fix is pointless.

The opponent was very clear in this matter, so no discussion allowed.

> Anyway, it seems I cannot fix this in UI - upon a file creation UI does not send any data regarding the file format, only the file itself. However, the server seems to assume the default delimiter to be the semicolon.

I have changed the default delimiter assumed by the server. What is left is to change the order of delimiters in the UI, let the comma be first in the select box. That would be all.
