### ISSUE TITLE
Add support for tooltips to labels

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#381]
E.g. for endpoint, name and so on...
Dr. Klimek would prefer small clickable icons to reveal them in order to support touch devices. When using mouse, reveal by when moving over is enough.

**Comment by istvan-satmari** [comment]
the directive added; remains the text

**Comment by istvan-satmari** [comment]
please provide some text descriptions so I can configure the tooltips for KB configuration + "Predicate sets"

**Comment by brodecva** [comment]
@istvan-satmari Hi, I would prefer you to provide temporary placholder text and then assign the pull request to me, and I will go through it and write my own. It will make it easier for me to come up with something in the right context, and I can also make sure it is not to overblown or too long. Hope it's OK that way.

**Comment by istvan-satmari** [comment]
Great, so I prepared the placeholders. See the latest develop commit in the /UI.
As for where to write the messages, the relevant files are:
- src/templates/kbconfig/template.html
- src/templates/setproperties/template.html

Only the messages inside the elements "<abbrc msg="TODO">" need to be replaced. (attribute "msg")

**Comment by brodecva** [comment]
Reopening to ask a question is it possible to hide to hide and prevent the tooltip displayed on hover to appear when the click-on variant is displayed. It does not look that good.

And here's a quote from a Book of Calm to ease you anger:
**"When you rest, you are a king surveying your estate. Look at the woodland, the peacocks on the lawn. Be the king of your own calm kingdom. "**

**Comment by istvan-satmari** [comment]
TODO: remove the hover
