### ISSUE TITLE
Add reexecute link to the screen with warnings displayed

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#384]

**Comment by istvan-satmari** [comment]
could you, please, elaborate? (which screen? task result?)

**Comment by brodecva** [comment]
> could you, please, elaborate? (which screen? task result?)

Sure, when a task finished, but with warnings, you can now let them be shown to you. On that screen, I reexecute button could accessible, so the user can do the reexecution immediately and not have to return back to the result display.

It was something brought up during the last meeting with the opponent.

**Comment by istvan-satmari** [comment]
"does not have to return back to the result display." - I assume you meant task list.
Presumably done provided I understood correctly. If not, during skype meeting we'll resolve this.
