### ISSUE TITLE
maybe add timeouts to AJAX calls

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#393]

**Comment by istvan-satmari** [comment]
Done, but my browser sometimes ignores it, if the timeout is set to a long time period. Also, the handling of the timeout is quite primitive, it only redirects user to an error screen. But, better than nothing, I guess.

**Comment by istvan-satmari** [comment]
"but my browser sometimes ignores it" - I think I know the cause of the problem (race condition); I'll provide fix later.

**Comment by tomas-knap** [comment]
Yes, for sure better, now you at least know that backend is not running

**Comment by istvan-satmari** [comment]
So I tried to fix the race condition, but it seems the problem lies elsewhere (browser? angular?). Most of the time it works, though.
