### ISSUE TITLE
Firefox always pre-fills authorization input controls

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#398]

**Comment by tomas-knap** [comment]
I would not spend time on that - we can say that we official do not support Firefox

**Comment by istvan-satmari** [comment]
I fixed it, but it seems the functionality is simply built into the Firefox and it cannot be simply turned off via JavaScript/HTML/CSS - the only way was to change type of the password input field to the "text" and it stopped pre-filling it.
So, naturally, what I did is, I changed the password input field to a classic "text" and once a user types anything, it gets immediately changed to "password". 
...so it's basically more of a hack, than a fix, but should suffice.



...stupid Firefox.
