### ISSUE TITLE
Tooltips do not support line breaks

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#399]
Well, they do when rolled over, but when clicked, they do not and it makes them a bit cumbersome to read, forcing the user to scroll to the right. Also it does not look good.
I tried to keep the text to one line, but sometimes this just cannot be done.
Can something be done about it?

**Comment by istvan-satmari** [comment]
Migrated to bootstrap's tooltips, it should be OK now.

**Comment by brodecva** [comment]
> Migrated to bootstrap's tooltips, it should be OK now.

You might hate me by now, and I don't blame you. But it is only now I have noticed that:
* The text in the tooltips is horizontally aligned to the center, which does not look good especially for longer tooltips, could you make it aligned to the left?
* And the tooltips displayed when rolled-over are maybe tad bit narrow (definitely narrower than when the question mark is clicked), making it hard to read the longer ones. Could you make the displayed tooltips as wide as those displayed when clicked?

**Comment by istvan-satmari** [comment]
TODO: remove the hover

**Comment by istvan-satmari** [comment]
Hover still supported, but behaviour is now the same as for the "clicking" option. This is to keep the user friendliness and consistency for desktop browsing.
