### ISSUE TITLE
Model: Task history

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#4]
- POSTPONED
- Prepare a model (i.e. a source of data) for task history.
- Create and configure Angular controllers for correctly displaying the data from the model.
- Model should be in a form of a JSON file. Its structure  should correspond to the one retrieved via REST API (see Confluence).
- i.e. a part of this task is also to create the JSON "demo file" and to use it as the model. Simply create the file with exemplar data.

**Comment by brodecva** [comment]
Hi, as this is not an essential (if I understand it correctly) for the 1st iteration (the more so for the presentation on June 20th), please postpone this issue, unless you have some valid reasons to not do so.
