### ISSUE TITLE
Add configuration option to switch between using e-mail confirmations and not

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#401]
Add to config.txt. Basically it would only suffice if it would just make the texts after sing up and password setting change from the one mentioning following the instruction in the email to simple confirmation. Otherwise it is already done on the server and it works.
We need this to allow easier basic docker installation, which would not require functional SMTP server and its configuration.
Thx!

**Comment by brodecva** [comment]
Actually redirecting or even automatical login in case the confirmations are turned of is highly preferrable.

**Comment by istvan-satmari** [comment]
For now only the screen was slightly changed (information panels and their text messages). I plan on adding an automatic login feature.

**Comment by istvan-satmari** [comment]
Automatic login upon signup should also be implemented by now.
