### ISSUE TITLE
Test!

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#405]
Quite important! Please find time to check everything, whenever you have spare minute.

**Comment by istvan-satmari** [comment]
Issue #1: Cannot import OpenData configuration downloaded from adol.cz/odalic-ui
java.lang.NullPointerException	at java.net.URI$Parser.parse(Unknown Source)	at java.net.URI.<init>(Unknown Source)	at java.net.URI.create(Unknown Source)	at ...

Server responds with status 500.

**Comment by istvan-satmari** [comment]
Issue #2: odalic-ui does not display error cause when server responds to the attempt of importing file as described in issue #1
