### ISSUE TITLE
Tooltips - is there a better way to show there is tooltip?

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#407]
Currently: 
![screen shot 2017-05-23 at 16 18 00](https://cloud.githubusercontent.com/assets/3014917/26358711/a5004b68-3fd3-11e7-8271-9e1b2ed244bc.png)

To be honest, I don't like this way of attaching tooltips - underlying the items with double line - one of the line is even crossing the text a bit. Would it be possible to e.g. add there "question mark icon"? And you can mouse over that icon to get some info? Or at least provide a different way (just one line, which is not that distracting)?

**Comment by istvan-satmari** [comment]
Yeah, whatever. Question mark icon for tooltip on mouse hover and clicking on the text toggles the tooltip (for handheld devices). No underlines.
