### ISSUE TITLE
Space between trash bin icon and the rest

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#408]
Run task with Book-v1.csv, where there is no label for first column, e.g.:
;Author;Series

![screen shot 2017-05-23 at 16 23 05](https://cloud.githubusercontent.com/assets/3014917/26359064/c1246828-3fd4-11e7-96fc-fe2f12d1a238.png)
The trash bin icon is not aligned, there is no space

**Comment by tomas-knap** [comment]
This bug is probably caused by: https://github.com/odalic/odalic-ui/issues/409

**Comment by brodecva** [comment]
Fixed as of https://github.com/odalic/odalic-ui/commit/f5e35e432b567825507ce73b74dc05ab4b01b566 .
