### ISSUE TITLE
First cell is strange - missing label!

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#409]
Run task with Books-v1.csv. Observe the result. there is no label for the first cell!
<img width="964" alt="screen shot 2017-05-23 at 16 45 26" src="https://cloud.githubusercontent.com/assets/3014917/26360019/4e582d0e-3fd7-11e7-9156-74c0fd6f994d.png">

**Comment by tomas-knap** [comment]
The file did not contain any header for the first column

**Comment by brodecva** [comment]
@KataBoku will fix that.
