### ISSUE TITLE
No subject column selected by default - so I cannot see what was determined by the algorithm as subject column

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#410]
I cannot see any subject column selected when I first come to the subject detection phase!

<img width="966" alt="screen shot 2017-05-23 at 16 53 11" src="https://cloud.githubusercontent.com/assets/3014917/26360515/9295e690-3fd8-11e7-8995-268eaa54a457.png">

By default, the lock should be unlocked and the column suggested by the algorithm selected! 
<img width="963" alt="screen shot 2017-05-23 at 16 54 00" src="https://cloud.githubusercontent.com/assets/3014917/26360490/80023f88-3fd8-11e7-9569-949d9d510acb.png">

**Comment by brodecva** [comment]
> I cannot see any subject column selected when I first come to the subject detection phase!

This is weird. The suggested one should be rendered in bold. Maybe there is some kind of rendering problem at Macs.

I will look into it right away.

**Comment by brodecva** [comment]
I have made the suggested column slightly grey and those suggested yellow. When a column is both the suggested and user-selected it has a slightly darker yellow color. The bold remains for the suggested column, but it is weird it does not display to you. Nevertheless the color distinction should be enough. Please confirm it is resolved as of https://github.com/odalic/odalic-ui/commit/46b19ace1e8435b4464421b8bd2d3c6f6f0a3b06 .

**Comment by tomas-knap** [comment]
Now it works, thanks
