### ISSUE TITLE
No label for node with no header in the original CSV file

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#411]
If there is no label in the input CSV file for certain column, then relation discovery phase shows empty node: 
![screen shot 2017-05-23 at 16 56 03](https://cloud.githubusercontent.com/assets/3014917/26360692/0cfc1d78-3fd9-11e7-87af-66e212807314.png)

I would expect to show something, e.g. column 1 or name of the class if classified

**Comment by brodecva** [comment]
Fixed as of https://github.com/odalic/odalic-ui/commit/f5e35e432b567825507ce73b74dc05ab4b01b566 .
