### ISSUE TITLE
Remove the home menu item and make the logo behave as the home item

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#421]

**Comment by istvan-satmari** [comment]
Whatever makes Klimek happy.




*cursing intensifies*

**Comment by brodecva** [comment]
Hi, one minor grip: the reddish background does not look good. The original orange was fine, there is no need to make more apparent that the logo is clickable by making the underground of different colour. Could you please fix that?

**Comment by brodecva** [comment]
Ah, taken back. I have noticed that it indicates on which page you are. Closing again.
