### ISSUE TITLE
Add tooltips to the large buttons (Reexecute, Save, ...)

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#423]

**Comment by istvan-satmari** [comment]
Well, it's not completely done... 
I really struggled with making tooltips work over \<button\> elements (over textual they are working fine). In the end I even did not completely solve it - I don't know what exactly, but something distorts the correct positioning of the tooltips above the buttons. For some reason, however, right, where they are most needed - i.e. taskresult, over the 3 buttons you mentioned - reexecute, save and cancel - they are working! So this is the only place where the tooltips are actually added.

For other buttons I do not know any other way than creating a custom tooltip, which is not an easy task at all. A directive was created for the purpose - btnexplain - but that is far from what one would call a 'tooltip' and even that doesn't work all the time (also has some other visually unappealing issues).

Sorry...
