### ISSUE TITLE
Syntax errors within the template files

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#436]
Not that important but there are some glaring syntax error in the template.html files, that even GitHub syntax marker notices and some of them are definitely not caused by the AngularJS integration.
The browsers does not seem to mind, but they might become a cause if not already of some hard to track bugs.

**Comment by istvan-satmari** [comment]
Could you please provide more details? I cannot seem to find any bugs in *.html files. (It would also be more likely if they happened in *.js files... do they?)

**Comment by brodecva** [comment]
Oh, sorry about that, here:

* odalic-ui/src/templates/taskresult/view/export/export.html contains &nbsp; entities without the trailing semi-colon.
*  odalic-ui/src/templates/createnewtask/template.html has at line 69 doubled right brace and quote sign (it is quite visible if you open the file to edit directly in the github)

**Comment by istvan-satmari** [comment]
Thanks, I would not have noticed. Strangely it does not seem to have had any negative impact, though...
