### ISSUE TITLE
All the exports identify themselves as CSV files in Firefox

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#437]
While the Chrome export now seem just fine, it seems that the solution screwed up the situation in Firefox: all files pretend to be CSV files when you click on the export buttons in Firefox.

**Comment by brodecva** [comment]
Hi, as I stressed during the last meeting let's come up with a solution that is not too hackicsh. For example @tomas-knap mentioned, that the files associates themself with Google Spreasheets because of this.

**Comment by istvan-satmari** [comment]
Reverted. As for chrome, won't fix - the current way of letting user download the exports is actually correct; we cannot alter the browser's behaviour. User simply has to press ctrl+s upon opening the corresponding export.
