### ISSUE TITLE
When user forgets to input either name or endpoint for newly created KB, but attempts to save at other than the first tab, nothing happens and he/she does not know why

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#440]
Any ideas? Maybe a simple warning, similar in appearance and location to the one received from the server when something else is amiss.

**Comment by istvan-satmari** [comment]
Upon clicking 'save', the user will be redirected to 'main' tab.
The only problem is, the external ui-tabset component does not work well at all and the tabset cannot be changed programmatically all the time (seems to be working only once per page load). This is really strange. But, it can be changed by clicking on any other ui component.
So what I did is once user clicks 'save', he is ALWAYS redirected to 'main' tab, not only upon a negative form validation. Hope that suffices.
