### ISSUE TITLE
KBs - Propose - tooltips + default values for object/data properties

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#443]
![screen shot 2017-05-30 at 10 13 51](https://cloud.githubusercontent.com/assets/3014917/26574274/00e7b888-4521-11e7-9c5e-088a05265454.png)

**Comment by brodecva** [comment]
The tooltip added as of https://github.com/odalic/odalic-ui/commit/5e58547ec793d7a357aa977b18dce8a84dc0d34a .

**Comment by brodecva** [comment]
The defaults solved in https://github.com/odalic/sti/issues/461 .
