### ISSUE TITLE
Make the Go to result button stand out

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#447]
In Czech:
> 2. V seznamu Tasků potom, co task doběhne, je nejočekávanější akce “Go to result”, což
ale z ikon nelze poznat.

**Comment by brodecva** [comment]
Not sure how, maybe add some glow?

**Comment by istvan-satmari** [comment]
Made a separate column for this.

**Comment by brodecva** [comment]
> Made a separate column for this.

Great idea! The only thing I would change though, is to display nothing in the cell instead of the Not available text when the result is not (yet) available. The text seems kinda out of place.

**Comment by brodecva** [comment]
>> Made a separate column for this.

> Great idea! The only thing I would change though, is to display nothing in the cell instead of the Not available text when the result is not (yet) available. The text seems kinda out of place.

I might fix that myself if I get to it first.

**Comment by brodecva** [comment]
I have removed the Not available label in https://github.com/odalic/odalic-ui/commit/5d9e143cc95e8530f9fe96947f72cf41a17482a1 . Closing.
