### ISSUE TITLE
Confusing task input file form

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#450]
In Czech:
> c. Sekce input file stále není přehledná. Možnosti jsou přidat nový soubor z disku
nebo z webu, ale podtím je ještě volba “Selected file”, kam se nově nahraný
soubor dostane mezi již existující. Myslím že by bylo vhodnějí mít možnosti
“Existující” nebo “Nový - místní”, “Nový z webu” a nenutit uživatele nejdřív nahrát
a pak ten nahraný ještě zvolit.

**Comment by brodecva** [comment]
Well this might me slightly more complicated. I will let @istvan-satmari assess the change complexity and together we will decide if it is manageable before the defence.

**Comment by istvan-satmari** [comment]
wontfix
Little gain from a relatively lot of work. The whole process of task creation would need to be changed (i.e. file would need to be uploaded inside a new task configuration for everything to work perfectly), so no.
