### ISSUE TITLE
Differentiate buttons with color

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#452]
In Czech:
> 1. Stále není jasné, na které z šedivých tlačítek má uživatel kdy kliknout. Chtělo by je to
barevně odlišit.

**Comment by brodecva** [comment]
Maybe add a slight blue tint to confirmation, affirmative buttons and slight orange tint to the cancelling, negative ones?

**Comment by istvan-satmari** [comment]
The colors may not be ideal, but from the UX perspective it works.

**Comment by brodecva** [comment]
> The colors may not be ideal, but from the UX perspective it works.

Well, they are not. I would go for the exact hue for both the blue and orange that is used in the rest of the application (e.g. for the intro text at the home page).
Also the tint is way to saturated. I would keep the perceived brightness of the original grey button and only add the respective blue or orange tint.

**Comment by brodecva** [comment]
> The colors may not be ideal, but from the UX perspective it works.

>> Well, they are not. I would go for the exact hue for both the blue and orange that is used in the rest of the application (e.g. for the intro text at the home page).
Also the tint is way to saturated. I would keep the perceived brightness of the original grey button and only add the respective blue or orange tint.

I might fix that myself if I get to it first.

**Comment by brodecva** [comment]
Please use something around HEX c6deee for affirmative button (I would not distinguish e.g. the reexecute and save, make them both the same color) and around HEX ffe3cf for the negative ones.
Also be consistent, e.g. in the groups form there are also grey buttons.
