### ISSUE TITLE
Clarify the meaning of the buttons in task result

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#453]
In Czech:
> 1. Stále není jasné, na které z šedivých tlačítek má uživatel kdy kliknout. Chtělo by je to
barevně odlišit.

**Comment by brodecva** [comment]
I would suggest to add a label on the left, where is now some empty space, that would clarify the usage of the buttons. Something like:
"What would you like to do with your provided feedback?"
But I leave it to open discussion for now.

**Comment by istvan-satmari** [comment]
I changed the colors... it should be enough ('cancel' is clearly something non-confirmative). I don't know what else can be done about it...

**Comment by brodecva** [comment]
>  I don't know what else can be done about it...

I would like to discuss the possibility of adding the label first, before ultimately closing this issue.

**Comment by brodecva** [comment]
Maybe "Provided feedback actions: Reexecute, Save, Cancel" would be better.
