### ISSUE TITLE
Improve the quality of code by getting rid of anonymous functions where possible and suitable

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#50]

**Comment by istvan-satmari** [comment]
We use anonymous functions for (!) the better code quality. (This was discussed a longer time ago)
Anyway, since this is an old issue and an irrelevant one, I close it.

**Comment by brodecva** [comment]
> We use anonymous functions for (!) the better code quality. (This was discussed a longer time ago)
Anyway, since this is an old issue and an irrelevant one, I close it.

Haha, OK. :-) I vaguely remember that. The problem I had was that an anonymous function is fine when it is short and its purpose obvious from its definition. Otherwise it is just an excuse to properly structure and name the functions in the code.
