### ISSUE TITLE
Proper and appealing form validation is missing

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#51]
As @tomas-knap noticed: when I do not fill certain important field and click create (I filled task id, but did not select a file.), nothing happens (which is strange).

Also: the form validation failed alert is awful - should be formatted using bootstrap - and if possible, done in on-site alerts (as is the case when uploading a file).

**Comment by brodecva** [comment]
@istvan-satmari Hi, we will discuss it at Skype, so I comment only to not forget it: When you close an issue such as this, I would expect that some code appears first in the remote repository and some pull request is linked to it (even if you are the one who will eventually accept it).

**Comment by istvan-satmari** [comment]
Yeah, got it. The code is now available, though.
