### ISSUE TITLE
Add buttons enabling export (in the form of Save file dialog) of annotated table (both JSON annotations and the extended CSV) and RDF (Turtle and JSON-LD)

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#53]
The REST API already supports these.

**Comment by istvan-satmari** [comment]
Done, though I kind of 'forgot' about the RDF-LD. (Requires sending headers I do not have configured at the moment.)

**Comment by brodecva** [comment]
> Done, though I kind of 'forgot' about the RDF-LD. (Requires sending headers I do not have configured at the moment.)

I think that is fine. But in the case you decide to drop it, just create an issue for the JSON-LD, so we won't forget about it.
