### ISSUE TITLE
Wrong class/disambiguation dialogs when one KB is used

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#60]
When running Odalic against one kb (Dbpedia), using the conf as in config/Jan, but specifying only DBPedia knowledge base, when the task result is available and I open details of classification/disambiguation, I got: 

![screen shot 2016-08-30 at 12 06 21](https://cloud.githubusercontent.com/assets/3014917/18085165/3bd28a98-6eaa-11e6-9300-b464d54cbeab.png)

![screen shot 2016-08-30 at 12 06 14](https://cloud.githubusercontent.com/assets/3014917/18085167/4135a7fe-6eaa-11e6-840d-d498ebc8f239.png)

Problem: In that case I should see only one KB textarea - DBPedia. It is automatically also considered to be primary KB.

**Comment by tomas-knap** [comment]
Also please check if it behaves correctly when you try to create new edge in Step 3 - relations - if the dialog looks the same as in case of classification/disambiguation

**Comment by brodecva** [comment]
This issue was moved to odalic/sti#131
