### ISSUE TITLE
Edges should be longer by default, so that one can read the label

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#61]
When I run Odalic for the books.csv file, I got: 

![screen shot 2016-08-30 at 12 31 16](https://cloud.githubusercontent.com/assets/3014917/18085970/e30f831c-6ead-11e6-8ac7-a99fa1899fcc.png)

The length of arrows is really small, no one can read the label. Please specify longer edges by default (relates with #59 ). I would expect something like below (in terms of the length of the edges): 

![screen shot 2016-08-30 at 12 31 26](https://cloud.githubusercontent.com/assets/3014917/18085935/bdbdf706-6ead-11e6-91be-f12e28a541a7.png)

**Comment by brodecva** [comment]
@tomas-knap @istvan-satmari I agree. At least in the initial state when the nodes are placed by the application.
Although it might be worthwhile to extend the edges and push the nodes away from each other even when the user modifies the layout of the graph later (but this might be left to later iterations).

**Comment by istvan-satmari** [comment]
Please, @brodecva, in more detail, what you meant. Besides that the lengths were corrected as requested.

**Comment by brodecva** [comment]
>Please, @brodecva, in more detail, what you meant. Besides that the lengths were corrected as requested.

Oh, forget about it. I realized how the layout is implemented and the idea just does not make sense. It works quite nicely as it is. Thanks!
