### ISSUE TITLE
Skip disambiguation checkbox - not working?

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#63]
The "skip disambiguation checkbox" does not work anyhow, so it is confusing. @KataBoku, am I correct?

![screen shot 2016-08-30 at 12 46 02](https://cloud.githubusercontent.com/assets/3014917/18086346/ba831344-6eaf-11e6-923b-703139b7f41f.png)

For column classification it is even more confusing: 
![screen shot 2016-08-30 at 12 45 21](https://cloud.githubusercontent.com/assets/3014917/18086332/ac223884-6eaf-11e6-953c-2ef294b7e656.png)

Solution: Hide if not implemented, correct/hide for classification dialog

**Comment by brodecva** [comment]
@tomas-knap @KataBoku This checkbox was meant function only as a part of feedback (and affect the next, repeated run). It may be so, that it will have immediate effect, but definitely not in this iteration. I have added it to the list of components to disable in #52 .
