### ISSUE TITLE
UI should display server errors it cannot deal with to the user

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#66]

**Comment by istvan-satmari** [comment]
Presumably done (with an exception of taskresult, but that is trivial - just around 2-3 lines of the same piece of code). 
Due to lack of an exact description I close the issue.
If needed, reopen a new one.

**Comment by brodecva** [comment]
> Presumably done

@istvan-satmari OK, I take it that from now, whenever an error message is delivered by the API, it is either processed by the client, or shown to the user.
