### ISSUE TITLE
Support repeated runs in the UI

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#68]
Enable and verify that the environemnt behaves correctly when the task is run again. Also the feedback should be sent before the next run.

**Comment by istvan-satmari** [comment]
Waiting for Kata until she corrects the taskresult screen. When the feedback is properly implemented and tested I'll deal with this issue.

**Comment by istvan-satmari** [comment]
Unfortunately taskresult has several bugs that need to be solved (if I make a change in taskresult - e.g. remove a concept, then feedback saving fails).
But the repeated run itself works.

**Comment by brodecva** [comment]
> Unfortunately taskresult has several bugs that need to be solved (if I make a change in taskresult - e.g. remove a concept, then feedback saving fails).

Please file the bugs, so we do not forget them. Or if the affected part is under development in some issue, report the found bug there. Thanks!
