### ISSUE TITLE
Model: Task result

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#7]
- Replace the model in (5) with a call to the model from (6), when the final decision about the UI architecture is made.
- The task should be relatively trivial, e.g. I assume we replace a call:
var taskResult = $.getJSON("./src/.../.../task-result-example.JSON");
...with another function to the model component.
- Use Apiary as a target where to send the requests to.

**Comment by brodecva** [comment]
Hi, as part of this (the history) might not be essential (if I understand it correctly) for the 1st iteration (the more so for the presentation on June 20th), please consider spltting this and postponing the history part of this issue, unless you have some valid reasons to not do so (for example the architecture you designed strongly and with good reason couples the history with the result provision).

**Comment by istvan-satmari** [comment]
Done.
