### ISSUE TITLE
Add 'leaving a column from export' form element

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#70]
_From @brodecva on September 2, 2016 11:25_

Story at https://grips.semantic-web.at/x/sBZsB .

_Copied from original issue: odalic/sti#139_

**Comment by tomas-knap** [comment]
@brodecva  Moved to 5th iter

**Comment by brodecva** [comment]
Waits for https://github.com/odalic/sti/issues/142 .

**Comment by tomas-knap** [comment]
Will not be implemented
