### ISSUE TITLE
Remove empty line at the end of the first column

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#81]
Running task using the file and latest develop (7. 9. morning): 
[Books-v2.csv.zip](https://github.com/odalic/odalic-ui/files/458639/Books-v2.csv.zip)

When I see the feedback, there is an empty line as last line in the first column: 

![screen shot 2016-09-07 at 10 31 51](https://cloud.githubusercontent.com/assets/3014917/18305260/fef0e366-74e6-11e6-8e84-0d2e6072f339.png)

Please remove that extra empty line

**Comment by tomas-knap** [comment]
Such empty line is in all tables (steps) of the feedback

**Comment by tomas-knap** [comment]
If easy to be solved, please try to solve that. If not, we can postpone

**Comment by brodecva** [comment]
> If easy to be solved, please try to solve that. If not, we can postpone

I let @istvan-satmari decide.

**Comment by istvan-satmari** [comment]
Unfortunately, I am not able to reproduce the bug. More info needed... (input and/or result json file)

**Comment by brodecva** [comment]
> Unfortunately, I am not able to reproduce the bug. More info needed... (input and/or result json file)

@tomas-knap links to it in this issue description .

**Comment by tomas-knap** [comment]
Can reproduce in Safari, but cannot reproduce in Chrome, where everything is working fine. 

Lets close that for now as won't fix

**Comment by brodecva** [comment]
> Can reproduce in Safari, but cannot reproduce in Chrome, where everything is working fine.
> Lets close that for now as won't fix

I will rather keep it open an move to the next iteration. This issue is well known and there is no need to further reproduce it. Happens whenever the CSV file ends with line separator (and therefore with an empty line).

**Comment by brodecva** [comment]
> Happens whenever the CSV file ends with line separator (and therefore with an empty line).

This is something that both the UI and the server should be able to deal with. No doubts.

**Comment by istvan-satmari** [comment]
As I previously mentioned, I am not able to reproduce the bug so I am not sure whether I fixed this,  but! we are using "GET .../tasks/simple_task/configuration/feedback/input"  REST API command, therefore if the problem persists, now it is most likely the server's fault.
