### ISSUE TITLE
Colored results for the second and other KBs

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#82]
When I run Odalic against 2 KB, the results from primary one are colored. But the results from the other (second) KB are not colored. Can we please have also colored results for the second and other KB? In general every KB should use its color.  The motivation is that as you see below, it is then hard to differentiate between the original cell content (Book) and the suggestion from the second KB (Person). 

![screen shot 2016-09-07 at 10 45 37](https://cloud.githubusercontent.com/assets/3014917/18305581/7776d0e2-74e8-11e6-9cac-453c3f43b4e6.png)

**Comment by tomas-knap** [comment]
If easy to be solved, please try to solve that. If not, we can postpone

**Comment by tomas-knap** [comment]
Please discuss with @istvan-satmari  whether this is correct approach. 

What I wanted is one color for each KB. But if possible, do it conceptually, so that we do not comment some code just because we need that now. Or if it is not possible to do that otherwise, please comment the changes in the code!! For example, i do not understand why src/templates/taskresult/controller.js was adjusted in https://github.com/odalic/odalic-ui/commit/2e2e4e1027d97d992b17b17710a52518bd9d6759

**Comment by tomas-knap** [comment]
TODO: 
@KataBoku + @istvan-satmari Discuss whether https://github.com/odalic/odalic-ui/commit/2e2e4e1027d97d992b17b17710a52518bd9d6759 is the right approach 
If yes, @KataBoku, please explain temporary hacks in your commit properly and merge to develop (after the discussion)

**Comment by brodecva** [comment]
@tomas-knap I talked with @KataBoku and she works on the fix that highlight every KB result.

Concerning the hard-coded KBs, I tend to agree with @KataBoku , that as long as we do not send the used KBs to her, I cannot blame her for hard-coding them in the client.
Yes, she could derive them from the actual result by iterating the keys, but that would only introduce another, even complicated temporary measure.
Ideally the used KBs should be a part of the task configuration, from which the client would read them and derive the color schema. But I cannot add them to the sent configuration either, as long as they are part of internal core configuration. It should be the task itself, that initiates the interpreter with the set of available KBs.
So my opininon is: we can either move the static configuration in the direction of the task itself, or accept the current state until proper KB management is introduced.

**Comment by tomas-knap** [comment]
Ok, so just @KataBoku please comment the temporal solution in the code. 
Also please write here the expectations you have regarding the KB names used.

Then we can consider this as being solved

**Comment by brodecva** [comment]
Works as of #88 .
