### ISSUE TITLE
Too dark orange for the primary KB

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#83]
![screen shot 2016-09-07 at 10 45 37](https://cloud.githubusercontent.com/assets/3014917/18305581/7776d0e2-74e8-11e6-9cac-453c3f43b4e6.png)

Adjust a bit

**Comment by brodecva** [comment]
@tomas-knap I had instructed @KataBoku to lighten the colors (but keep the overall Odalic color schema).

**Comment by tomas-knap** [comment]
Ok, thanks!

**Comment by brodecva** [comment]
Fixed as of #88 .
