### ISSUE TITLE
Adjust landing page

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#84]
Some better intro info

**Comment by brodecva** [comment]
@tomas-knap I think removing the Facebook logo, comments in the footers, that test of headers formatting, disabling Login and adding a short text, some thing like "Follow by Creating a new task." would suffice for now.

**Comment by brodecva** [comment]
> would suffice for now.

Unless @tomas-knap wants to add something specific.

**Comment by tomas-knap** [comment]
Yes, something like that. Assigning to myself, I can do that.

**Comment by tomas-knap** [comment]
Adjusted for the demo, but did not commit to the repo, we would anyway have different landing page for iteration 3 (probably list of tasks?)
