### ISSUE TITLE
Get also labels when resource is obtained via lodlive

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#85]
Currently (see second row, first column): 
![screen shot 2016-09-07 at 11 30 21](https://cloud.githubusercontent.com/assets/3014917/18307000/b52773e6-74ee-11e6-93e7-bcdc94920fb3.png)

So the label for the resource obtained via lodlive is missing

**Comment by brodecva** [comment]
Let us also find out if the LodLive works for other bases than the DBpedia. And then decide upon the mean of label retrieval.

**Comment by tomas-knap** [comment]
I would suggest to postpone to iteration 6 and focus in iteration 5 on a simple browser window showing dereferenced URLs

**Comment by tomas-knap** [comment]
@brodecva  Please assign to someone to test whether lodlive works also with other KBs then Dbpedia. Then we may decide whether to further improve or not

**Comment by tomas-knap** [comment]
For now Won't fix, may be reopened after https://github.com/odalic/odalic-ui/issues/127 is solved
