### ISSUE TITLE
Relation graph doesn't work correctly with DBpedia Clone

### ISSUE THREAD

**Issue by KataBoku** [odalic/odalic-ui#87]
test and repair it in branch more-kbs

**Comment by tomas-knap** [comment]
@KataBoku , please specify on which commit and which data this happens. Also describe steps to reproduce. Then assign to istvan. 

Never write "test and repair it in branch XX" as changes are always done to develop or in a separate branch!

**Comment by KataBoku** [comment]
When I created more than one new task without refreshing of web page, then graph of relations didn't work correctly.

**Comment by istvan-satmari** [comment]
Graphvis directive scoping problem. Should be fixed by now; I cannot seem to be able to reproduce the bug anymore.
