### ISSUE TITLE
Controller: Task history

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/odalic-ui#9]
- Implement the controller part for task history screen.
- The functionality should include at least the following: task deletion (from a history only, not necessarily a cancelation of a task), task cloning.
- So the task has 2 major parts: REST requests (to Apiary) and callback functions, which refreshes the UI after success or failure of the REST requests.

**Comment by brodecva** [comment]
Hi, as this is not an essential (if I understand it correctly) for the 1st iteration (the more so for the presentation on June 20th), please postpone this issue, unless you have some valid reasons to not do so.
