### ISSUE TITLE
Display prefixed form of the URIs for entities and provide prefix for label wherever it can be confused with similar label from another namespace (e.g. relation labels).

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#92]
To reproduce - run 
[Books-v2.csv.zip](https://github.com/odalic/odalic-ui/files/463390/Books-v2.csv.zip) and then go to disambiguation of "Jost Friedrich"

When URI of certain resource is a bit longer, I can see only part of that: 

![screen shot 2016-09-09 at 09 25 13](https://cloud.githubusercontent.com/assets/3014917/18379120/026f2f80-7671-11e6-8c6e-d8a185a23d21.png)

Solution: 
1) Make the dialog a bit bigger
2) There must be scrollbar automatically appearing in such cases

**Comment by brodecva** [comment]
We have problems implementing this. I propose to postpone it until the prefixes are implemented.

**Comment by brodecva** [comment]
Note that there may be more than one prefix for a KB, it should be a pair of prefix alias, and the actual URI prefix that will be substituted by the prefix.

**Comment by brodecva** [comment]
Also think about whether this should be a separate service, or the prefixes should become a part of the model and to be sent with every URI.

**Comment by brodecva** [comment]
Waits for https://github.com/odalic/sti/issues/171 .

**Comment by brodecva** [comment]
Every entity sent from the server from now on contains "prefixed" field, which contains the URI prefixed by a prefix set in configuration file on the server. If no such exists, its content is the same as of the already existing field "resource". If you want to test that, get the latest develop version and update the sti.properties file and add the PrefixMapping.ttl file to the config folder.

**Comment by brodecva** [comment]
From now the entity object sent from the server contains also "prefix" and "tail" fiels. Prefix field is an object containing "with" (the actual prefix string) and "what" (associated URI) attributes. Tail is what is left of the expanded resource URI after the prefix separator.

**Comment by brodecva** [comment]
For details see the REST API spec proposal.
